package metier.epsEnum;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Collection;
import java.util.EnumSet;
import java.util.List;

public enum BakingBeanEnum implements Serializable{

	//Page("BB from facesConfig")
	bankParam("bankEpsBackingBean"),	
	bankParamSearch("bankEpsSearchBackingBean"),
	login("loginBean"),
	//ADDED BY TARIK
	cardFees("CardFeesBackingBean"),
	cardFeesSearch("CardFeesSearchBB"),
	cardFeesStatus("CardFeesStatusBackingBean"),
	cardFeesStatusSearch("CardFeesStatusSearchBB"),
	cardProduct("CardProductBackingBean"),
	cardProductSearch("CardProductSearchBB"),
	renewalCondition("RenewalConditionBackingBean"),
	renewalConditionSearch("RenewalConditionSearchBB"),
	pinMailer("PinMailerBackingBean"),
	pinMailerSearch("PinMailerSearchBB"),
	callAction("CallActionBackingBean"),
	callActionSearch("CallActionSearchBB"),
	callReasonCard("CallReasonCardBackingBean"),
	callReasonCardSearch("CallReasonCardSearchBB"),
	callCard("CallCardBackingBean"),
	callCardSearch("CallCardSearchBB"),
	stopListHistoryCard("StopListHistoryCardBackingBean"),
	stopListHistoryCardSearch("StopListHistoryCardSearchBB"),
	stopListHistoryBin("StopListHistoryBinBackingBean"),
	stopListHistoryBinSearch("StopListHistoryBinSearchBB"),
	stopListHistoryRange("StopListHistoryRangeBackingBean"),
	stopListHistoryRangeSearch("StopListHistoryRangeSearchBB"),
	emvScriptDefinition("EmvScriptDefinitionBackingBean"),
	emvScriptDefinitionSearch("EmvScriptDefinitionSearchBB"),
	emvScriptStatusSearch("CardEmvScriptStatusSearchBB"),
 	actifRange("CardActifRangeBB"),
 	actifRangeSearch("CardActifRangeSearchBB"),
 	atmProfile("AtmProfileBackingBean"),
 	atmProfileSearch("AtmProfileSearchBB"),
 	profilDefinition("ProfilManagementBB"),
 	profilDefinitionSearch("ProfilManagementSearchBB"),
 	command("AtmCommandBackingBean"),
 	configManagement("ConfigMgtBackingBean"),
 	configManagementSearch("ConfigMgtSearchBB"),
 	atmIsoManagement("IsoManagementBB"),
 	atmIsoManagementSearch("IsoManagementSearchBB"),
 	accountCancelledTrx("AccountCancelledTrxBB"),
 	accountCancelledTrxSearch("AccountCancelledTrxSearchBB"),
 	atmMonitoring("AtmMonitoringBB"),
 	fdkManagement("FdkManagementBackingBean"),
 	fdkManagementSearch("FdkManagementSearchBB"),
 	atmDistribution("AtmDistributionBackingBean"),
 	atmDistributionSearch("AtmDistributionSearchBB"),
 	alertParam("AtmAlertParamBackingBean"),
 	alertHistSearch("AtmAlertHistSearchBB"),
 	standingAccountParamSearch("StandingAccountSearchBB"),
 	fullAuthorization("FullAuthBackingBean"),
 	riskLevel("RiskLevelBackingBean"),
 	visaExceptionFile("VisaExceptionFileBB"),
 	bankExceptionFile("BankExceptionFileBB"),
 	atmCommandSearch("AtmCommandSearchBB"),
 	terminal("TerminalBB"),
 	terminalSearch("TerminalSearchBB"),
 	emvScriptByCard("EmvScriptByCardBB"),
 	emvScriptByProduct("EmvScriptByProductBB"),
 	printLayoutEnv("PrintLayoutEnveloppeBB"),
 	printLayoutEnvSearch("PrintLayoutEnveloppeSearchBB"),
 	changeProduct("ChangeProductBackingBean"),
 	changeProductSearch("ChangeProductSearchBB"),
 	visaBins("VisaBinsBackingBean"),
 	visaBinsSearch("VisaBinsSearchBB"),
 	visaArdef("VisaArdefBackingBeen"),
 	visaArdefSearch("VisaArdefSearchBB"),
 	masterCardAcqBin("MasterCardAcqBinBackingBean"),
 	masterCardAcqBinSearch("MasterCardAcqBinSearchBB"),
 	masterCardRanges("MasterCardRangesBackingBean"),
 	masterCardRangesSearch("MasterCardRangesSearchBB"),
	//ADDED BY AKIM NKA
	//----transaction parametrage
	ClearingInfoParam("clearingBakingBean"),
	ClearingInfoParamSearch("clearingSearchBB"),
	NetworkClearingCriteriaParam("networkClearingCriteriaBakingBean"),
	NetworkClearingCriteriaParamSearch("networkClearingCriteriaSearchBB"),
	TransactionCtrlCodeParam("transactionCtrlCodesBakingBean"),
	TransactionCtrlCodeParamSearch("transactionCtrlCodesSearchBB"),
	MatchingParamSearch("matchingCriteriaSearchBB"),
	MatchingParam("matchingCriteriaBakingBean"),
	CardholderFeesParam("cardholderFeesBakingBean"),
	CardholderFeesParamSearch("cardholderFeesSearchBB"),
	MerchantFeesParam("merchantFeesBakingBean"),
	MerchantFeesParamSearch("merchantFeesSearchBB"),
	ValueDateCalParam("valueDateCalculationBakingBean"),
	ValueDateCalParamSearch("valueDateCalculationSearchBB"),
	ChargebackParam("chargebakReasonBakingBean"),
	ChargebackParamSearch("chargebakReasonSearchBB"),
	PotentielReasonParam("potentielReasonBakingBean"),
	PotentielReasonParamSearch("potentielReasonSearchBB"),
	CopyReqReasonParam("copyRequestReasonBakingBean"),
	CopyReqReasonParamSearch("copyRequestReasonSearchBB"),
	AccountingEntriesParam("accountingEntriesParamBakingBean"),
	AccountingEntriesParamSearch("accountingEntriesParamSearchBB"),
	//----transaction mangement
	ProgramIndexSearch("programIndexSearchBB"),
	ProgramIndexParam("programIndexBB"),
	
	ProgramDefinitionSearch("programDefinitionSearchBB"),
	ProgramDefinitionParam("programDefinitionBB"),
	
	ProgramConversionSearch("programConversionSearchBB"),
	ProgramConversionParam("programConversionBB"),
	
	ProgramGiftSearch("programGiftSearchBB"),
	ProgramGiftParam("programGiftBB"),
	
	ProgramRedemptionSearch("programRedemptionSearchBB"),
	ProgramRedemptionParam("programRedemptionBB"),
	
	ControlModif("controlBean"),
	RecycleModif("recycleBean"),
	dynamicReport("GenerateReportDynamic"),
	authorizationLists("authoListsSBean"),
	cardEmergency("cardEmergencyBB"),
	cardErrorAjustement("cardErrorAjustementBB"),
	
	ArnGenerationSearch("arnGenerationSearchBB"),
	ArnGenerationParam("arnGenerationBB"),
	//authorizationLists("authoListsBBean"),
	
	AcqTransactionRemittance("acqTransactRemittanceSearchBB"),
	AcqTransactionRemittanceHist("acqTransactRemittanceHistSearchBB"),
	AcquirerTransaction("acquirerTransactionSearchBB"),
	AcquirerTransactionControl("acquirerTransactControlSearchBB"),
	AcquirerTransactionHist("acquirerTransactHistSearchBB"),
	AcquirerTransactionRecycle("acquirerTransactRecycleSearchBB"),
	AcquirerTransactionReject("acquirerTransactRejectSearchBB"),
	AcqValidTransaction("acqValidTransactionSearchBB"),
	IncomingMasterTransaction("incomingMasterTransactionSearchBB"),
	IncomingMasterTransactionHist("incomingMasterTransactHistSearchBB"),
	IncomingVisaTransaction("incomingVisaTransactionSearchBB"),
	IncomingVisaTransactionHist("incomingVisaTransactHistSearchBB"),
	MasterCyChargeback("masterCyChargebackSearchBB"),
	MerchantTransSettlement("merchantTransactSettlementSearchBB"),
	MerchantTransSettlementHist("merchantTransactSettlementHistSearchBB"),
	SuspectedChargeback("suspectedChargebackSearchBB"),
	VisaCyChargeback("visaCyChargebackSearchBB"),
	CaptureTransaction("captureTransactionBean"),
	CaptureSearch("captureTransactSearch"),
	//----merchant
	ManagementParam("managementBakingBean"),
	ManagementSearch("managementSearchBB"),
	MerchantAccounts("merchantAccountBakingBean"),
	MerchantAccountsSearch("merchantAccountSearchBB"),
	MerchantActivityParam("merchantActivityBBean"),
	MerchantActivitySearch("merchantActivitySB"),
	MerchantChargingParam("merchantChargingBBean"),
	MerchantChargingSearch("merchantChargingSB"),
	MerchantCommission("merchantComissionBakingBean"),
	MerchantCommissionSearch("merchantComissionSearchBB"),
	MerchantDataParam("merchantDataBBean"),
	MerchantDataParamSearch("merchantDataSB"),
	MerchantFLimitSearch("merchantFLimitSearchBB"),
	MerchantFloorLimitParam("merchantFLimitBakingBean"),
	MerchantLimitParam("merchantLimitBakingBean"),
	MerchantLimitSearch("merchantLimitSearchBB"),
	MerchantParam("merchantBackingBeans"),
	MerchantParamSearch("merchantSearchBB"),
	MerchantValidationParam("merchantValidationBBean"),
	MerchantValidationSearch("merchantValidationSB"),
	MerchantVarCommissionParam("merchantVarComissionBakingBean"),
	MerchantVarCommissionSearch("merchantVarComissionSearchBB"),
	PosManagementParam("posManageBean"),
	PosManagementSearch("posManageSB"),
	CaptureAutho("captureAuthoBBean"),
	//----pos
	PosEmvCaPKSearch("posEmvCaPKSearchBB"),
	PosEmvCaPKParam("posEmvCaPKBB"),
	PosFitSearch("posFitSearchBB"),
	PosFitParam("posFitDBB"),
	PosEmvAIDSearch("posEmvAIDSearchBB"),
	PosEmvAIDParam("posEmvAIDBB"),
	StopListSearch("stopListSB"),
	StopListParam("stopListBBean"),
	PosTerminalCollectParam("posTerminalCollectBean"),
	PosTerminalCollectSearch("posTerminalCollectSB"),
	PosTerminalParam("posTerminalBean"),
	PosTerminalReconParam("posTerminalReconBean"),
	PosTerminalReconSearch("posTerminalReconSB"),
	PosTerminalSearch("posTerminalSB"),
	StopListPos("stopListPosSB"),
	//----report
	CutOff("cutOffBBean"),
	ReportBatchGroup("reportBatchGroupBBean"),
	ReportBatchGroupSearch("reportBatchGroupSBean"),
	ReportDetails("reportDefinitionBBean"),
	ReportDetailsSearch("reportDefinitionSBean"),
	ReportGroup("reportGroupBBean"),
	ReportGroupSearch("reportGroupSBean"),
	ReportProcessing("reportProcessingBBean"),
	ReportUserGroup("reportUserGroupBBean"),
	ReportUserGroupSearch("reportUserGroupSBean"),
	//----parametre generaux
	ActionDefinitionSearch("actionDefinitionSearchBB"),
	ActionDefinitionParam("actionDefinitionBean"),
	FunctionSearch("functionSearchBB"),
	FunctionParam("functionBean"),
	TerminalBrandSearch("terminalBrandSearchBB"),
	TerminalBrandParam("terminalBrandBean"),
	MessageSearch("messageSearchBB"),
	MessageParam("messageBean"),
	AtmTrxCodeSearch("atmTrxCodeSearchBB"),
	AtmtrxCodeParam("atmTrxCodeBean"),
	OnlineEventSearch("onlineEventSearchBB"),
	OnlineEventParam("onlineEventBean"),
	TransactionTypeSearch("transactionTypeSearchBB"),
	TransactionTypeParam("transactionTypeBean"),
	EntityLengthControlParam("entityLengthControlBean"),
	EntityLengthControlSearch("entityLengthControlSearchBB"),	
	EmailManageParam("emailManageBB"),
	EmailManageSearch("emailManageSB"),
	AlertActionParam("alertActionParamBB"),
	AlertActionSearch("alertActionParamSB"),
	EventAlertParam("eventAlertParamBB"),
	EventAlertSearch("eventAlertParamSB"),
	InterfaceAlertParam("interfaceAlertParamBB"),
	InterfaceAlertSearch("interfaceAlertParamSB"),
	NDCAlertParam("nDCAlertParamBB"),
	NDCAlertSearch("nDCAlertSB"),
	OnlineAlertParam("onlineAlertParamBB"),
	OnlineAlertParamSearch("onlineAlertParamSB"),
	
	
	//end AKIM NKA
	userRoles("userRolesBB"),
	userParam("userParamBB"),
	userParamSearch("userParamSearchBB"),
	branchParam("branchBackingBean"),
	branchParamModify("branchBackingBean"),
	branchParamSearch("branchSearchBB"),
	cityParam("cityBackingBean"),
	cityParamSearch("citySearchBB"),
	centerParam("centerBackingBean"),
	centerParamSearch("centerSearchBB"),
	currencyCountryParam("currencyCountryBackingBean"),
	currencyCountryParamSearch("currencyCountrySearchBB"),
	statusReasonParam("statusReasonBackingBean"),
	statusReasonParamSearch("statusReasonSearchBB"),
	processingParam("processingBackingBean"),
	processingParamSearch("processingSearchBB"),
	cardStoppedParam("cardStoppedBB"),
	cardStoppedSearchParam("cardStoppedSearchBB"),
	accountTypeParam("accountTypeBackingBean"),
	accountTypeParamSearch("accountTypeSearchBB"),
	hostMaintenanceFeesParam("HostMaintenanceFeesBakingBean"),
	hostMaintenanceFeesParamSearch("HostMaintenanceFeesSearchBB"),
	extendedDataTableControlBean("ExtendedDataTableControlBean"),
	extendedDataTableBean("ExtendedDataTableBB"),
	
	//Added by BATHAOUI
	
	/////////////////RiskManagement///////////////////////////////////////////
	binStoppedParam("binStoppedBB"),
	binStoppedSearchParam("binStoppedSearchBB"),
	rangeStoppedParam("rangeStoppedBB"),
	rangeStoppedSearchParam("rangeStoppedSearchBB"),
	binStopMerchantMcc("binStopMerchantMccBB"),
	binStopMerchantMccSearch("binStopMerchantMccSearchBB"),
	cardStopMerchantMcc("cardStopMerchantMccBB"),
	cardStopMerchantMccSearch("cardStopMerchantMccSearchBB"),
	rangeStopMerchantMcc("rangeStopMerchantMccBB"),
	rangeStopMerchantMccSearch("rangeStopMerchantMccSearchBB"),
	binStopCountry("binStopCountryBB"),
	binStopCountrySearch("binStopCountrySearchBB"),
	cardStopCountry("cardStopCountryBB"),
	cardStopCountrySearch("cardStopCountrySearchBB"),
	rangeStopCountry("rangeStopCountryBB"),
	rangeStopCountrySearch("rangeStopCountrySearchBB"),
	networkStopList("networkStopListBB"),
	networkStopListSearch("networkStopListSearchBB"),
	cardForValidation("cardForValidationSearchBB"),
	cardPersonalization("cardPersonalizationBB"),
	cardChargingParam("cardChargingBB"),
	cardChargingParamSearch("cardChargingSearchBB"),
	cardOperationParamSearch("cardOperationSearchBB"),
	cardOperationParam("cardOperationBB"),
	interfaceParam("interfaceBackingBean"),
	interfaceParamSearch("interfaceSearchBB"),
	interfaceOperationParam("interfaceOperationBackingBean"),
	interfaceOperationParamSearch("interfaceOperationSearchBB"),
	workingDaysParam("workingDaysBackingBean"),
	workingDaysParamSearch("workingDaysSearchBB"),
	cardDataParam("cardDataBackingBeanParam"),
	cardDataParamSearch("cardDataSearchBB"),
	pinDeliveryProcess("pinDeliveryProcessBB"),
	cardDeliveryProcess("cardDeliveryProcessBB"),
	/////////////////HOST///////////////////////////////////////////
	hostDepositHistory("hostDepositHistory"),
	hostDepositHistorySearch("hostDepositHistorySearch"),
	hostDepositValidation("hostDepositValidationBB"),
	hostTransfertValidation("hostTransfertValidationBB"),
	hostInterestFeesParam("HostInterestFeesBakingBean"),
	hostInterestFeesParamSearch("HostInterestFeesSearchBB"),
	hostClientCapture("hostClientBackingBean"),
	HostClientSearch("hostClientSearchBB"),
	hostAccountCapture("hostAccountBackingBean"),
	hostAccountCaptureAdd("hostAccountBackingBean"),
	hostAccountSearch("hostAccountSearchBB"),
	hostDeviceAccountCapture("hostDeviceAccountBackingBean"),
	hostDeviceAccountCaptureAdd("hostDeviceAccountBackingBean"),
	hostDeviceAccountSearch("hostDeviceAccountSearchBB"),	
	hostDepositCapture("hostDepositBackingBean"),
	hostDepositSearch("hostDeviceAccountSearchBB"),	
	hostTransferCapture("hostTransferBackingBean"),
	hostTransferSearch("hostTransferSearchBB"),		
	hostValidationDeposit("hostValidationDepositBB"),
	hostValidationTransfer("hostValidationTransferBB"),
	hostTransferHistSearch("hostTransferHistSearchBB"),
	hostTransferHistCapture("HostTransferHistBakingBean"),
	hostClientTransactionAccountSearch("hostClientTransactionAccountBB"),
	hostClientTransactionAccount("hostClientTransactionAccountBB"),	
	hostChequeRequestSearch("chequeRequestSearchBB"),
	hostChequeRequest("chequeRequestBB"),	
	hostChequeRequestHistSearch("chequeRequestHistBB"),
	hostChequeRequestHist("chequeRequestHistBB"),	
	//ATM 
	messagesManagement("messagesManagementBB"),
	messagesManagementSearch("messagesManagementSearchBB"),
	suspectTransaction("suspectTransaction"),
	atmActivitySearch("atmActivitySearchBB"),
	atmActivity("atmActivitySearchBB"),
	atmSettlementSearch("atmSettlementBB"),
	atmSettlement("atmSettlementBB"),
	
	//CREDIT
	accountManagementParam("accountManagementParamBB"),
	accountManagementParamSearch("accountManagementParamSearchBB"),
	interestMccParam("interestMccParamBB"),
	interestMccParamSearch("interestMccParamSearchBB"),
	interestParam("interestParamBB"),
	interestParamSearch("interestParamSearchBB"),
	lateFeeParam("lateFeeParamBB"),
	lateFeeParamSearch("lateFeeParamSearchBB"),
	cycleDatesParam("cycleDatesBB"),
	cycleDatesSearch("cycleDatesSearchBB"),
	penaltyFeesParam("penaltyFeesParamBB"),
	penaltyFeesParamSearch("penaltyFeesParamSearchBB"),
	overdrawnFeesParam("overdrawnFeesBB"),
	overdrawnFeesSearch("overdrawnFeesSearchBB"),
 	creditAccount("creditAccountBBean"),
 	creditAccountSearch("creditAccountSearchBB"),
 	creditCollateral("creditCollateralBBean"),
 	creditCollateralSearch("creditCollateralSBean"),
 	creditTransactionParam("creditTransParamBBean"),
 	creditTransactionParamSearch("creditTransParamSBean"),
 	creditTransaction("CreditTransactionsBackingBean"),
 	creditTransactionSearch("CreditTransactionsSearchBB"),
 	creditTransactionHist("CreditTrxHistBackingBean"),
 	creditTransactionHistSearch("CreditTrxHistSearchBB"),
	AccountCaptureSearch("AccountCaptureTrxSearch"),
	AccountCaptureTrx("AccountCaptureTrxBean"),
	AccountPaiementHist("accountPaiementHistSB"),
	AccountPaiement("accountPaiementSB"),
	accountOnlineActivity("accountOnlineActivity"),
	creditForValidation("creditForValidationBB"),


 	//CALL CENTER
 	affectationCall("affectationCallBB"),
 	suiviCall("suiviCallBB"),
 	
 	//Visa chargeBack
 	visaChargeBack("visaCyChargbackBB"),
 	
 	//EMV
 	emvVerification("emvVerificationBB"),
 	emvVerificationSearch("emvVerificationSearchBB"),
 	emvLimitIndex("emvLimitIndexBB"),
 	emvLimitIndexSearch("emvLimitIndexSearchBB"),
 	
	// Added by Jurin
 	groupRoles("groupRolesBB"),
	onlineControlParam("onlineControlParamBBean"),
	onlineControlParamSearch("onlineControlParamSBean"),
	epsProfileDefinition("epsProfileBBean"),
	epsProfileSearch("epsProfileSBean"),
	AuthoFees("authoFeesBBean"),
	AuthoFeesSearch("authoFeesSBean"),
	actionManagement("actionManagementBBean"),
	actionManagementSearch("actionManagementSBean"),
	actionTranslation("actionTranslationBBean"),
	actionTranslationSearch("actionTranslationSBean"),
	cAuthAmtOrig("controlAuthAmtOrigBean"),
	cAuthAmtOrigSearch("controlAuthAmtOrigSBean"),
	emvControlParam("emvControlParamBBean"),
	InternalRouting("internalRBBean"),
	InternalRoutingSearch("internalRSBean"),
	limitsAuth("limitsAuthBBean"),
	limitsAuthSearch("limitsAuthSBean"),
	limitsByProcess("limitsByProcessBBean"),
	limitsByProcessSearch("limitsByProcessSBean"),
	limitsTotal("limitsTBBean"),
	limitsTotalSearch("limitsTSBean"),
	msgControlParam("msgControlParamBBean"),
	msgControlParamSearch("msgControlParamSBean"),
	rangeParameters("rangeParametersBBean"),
	rangeParametersSearch("rangeParametersSBean"),
	
	authorizationReconciliation("authoReconciliationSBean"),
	authorizationSaf("authoSafSBean"),
	authorizationSafLogs("authoSafLogSBean"),
	interfacesExploitation("interfacesExpBBean"),
	interfacesMonitoring("interfacesMonBBean"),
	
	// Added by FARID
	blackListCountryParam("blackListCountryBBean"),
	blackListCountrySearchParam("blackListCountrySearchBBean"),
	blackListMccParam("blackListMccBBean"),
	blackListMccSearchParam("blackListMccSearchBBean"),
	fraudAlertesParam("FraudAlertesBBean"),
	fraudAlertesSearchParam("FraudAlertesSearchBBean"),
	mccExcludingParam("MccExcludingBBean"),
	mccExludingSearchParam("MccExcludingSearchBBean"),
	statuscCardTrxFraudParam("StatusCardTrxFraudBBean"),
	statuscCardTrxFraudSearchParam("StatusCardTrxFraudSearchBB"),
	
	welcomePage("welcomeBB"),
	epsAdministrationMessageParam("epsAdministrationMessageBB"),
	epsAdministrationMessageSearch("epsAdministrationMessageSearchBB"),
	historyUserOpeartionSearch("historyUserOpeartionSearchBB"),
	historyUserOpeartionCapture("historyUserOpeartionBB"),
	epsMemosParam("epsMemosBB"),
	epsMemosSearch("epsMemosSearchBB"),
	epsPlanningSearch("epsPlanningSearchBB"),
	epsPlanningParam("epsPlanningBB"),	
	
	//Added By MARIAM
	
	mccParam("MccBakingBean"),
	mccParamSearch("MccSearchBB"),
	langueParamSearch("LangueSearchBB"),
	langueParam("LangueBakingBean"),
	networkParam("networkBackingBean"),
	networkParamSearch("networkSearchBB"),
	tagManagemntParamSearch("TagManagementSearch"),
	TagManagementParam("TagManagementBB"),
	daysOffParam("DaysOffBB"),
	daysOffParamSearch("daysOffSearchBB"),
	networkCardTypeParam("NetworkCardTypeBB"),
	networkCardTypeParamSearch("NetworkCardTypeSearchBB"),
	DailyRateParam("DailyRateBB"),
	DailyRateParamSearch("DailyRateSearchBB"),
	crossRateParam("CrossRateBB"),
	crossRateParamSearch("CrossRateSearchBB"),
	
	//Module credit
	AuthoManual("AuthoManualBBean"),
	OrderClearingTrxParam("OrderClearingTrxParamBB"),
	OrderClearingTrxSearch("OrderClearingTrxSearchBB"),	
	AdminStatusSearch("AdminStatusSearchBB"),
	AdminStatusParam("AdminStatusParamBB"),
	
	// ADDED BY ZAKARIA
	cassettesSearch("cassettesSearchBB"),
	cassettes("cassettesBB"),
	replayManagementSearch("replayManagementSearchBB"),
	replayManagement("replayManagementBB"),
	responseManagementSearch("responseManagementSearchBB"),
	treeAtmParameters("AtmParametersBB"),
	responseManagement("responseManagementBB");
	
	
	String code;		

    private BakingBeanEnum(String code) {
        this.code = code;
    }
	 /**
     * @return le code
     */
	public String getCode() {
        return code;
    }

    /**
     * Méthode de comparaison
     * @param code code à comparer
     * @return Vrai si le code passé en paramètre correspond au code de l'énum, faux sinon.
     */
    public boolean is(String code) {
        return this.code.equals(code);
    }

    /**
     * liste des états pour décisions sur règlement
     * @return une liste des états
     */
  

    /**
     * construit une collection de codes
     * @param etats la liste des états
     * @return un collection de codes
     */
    /*public static Collection<String> toCodeCollection(EnumSet<BakingBeanEnum> etats) {

        List<String> codes = new ArrayList<String>();
        for (BakingBeanEnum etat : etats) {
            codes.add(etat.getCode());
        }
        return codes;
    }*/
}
