package dao.Hibernate.Model;

import java.math.BigDecimal;
import java.util.Date;


// Generated 4 août 2009 08:59:29 by Hibernate Tools 3.2.2.GA

/**
 * ApplicationTraces generated by hbm2java
 */
public class ApplicationTraces implements java.io.Serializable {

	private ApplicationTracesId id;
	private BigDecimal lineNumber;
	private String actionToTake;
	private String actionAFaire;
	private String systemError;
	private String packageName;
	private String functionName;
	private String traceLevel;
	
	private boolean logo_fatal;
	private boolean logo_warn;
	private boolean logo_normal;
	private boolean action_en;
	private boolean action_fr;

	public ApplicationTraces() {
	}

	public ApplicationTraces(ApplicationTracesId id,
			BigDecimal lineNumber, String actionToTake, String actionAFaire,
			String systemError, String packageName, String functionName,
			String traceLevel) {
		this.id = id;
		this.lineNumber = lineNumber;
		this.actionToTake = actionToTake;
		this.actionAFaire = actionAFaire;
		this.systemError = systemError;
		this.packageName = packageName;
		this.functionName = functionName;
		this.traceLevel = traceLevel;
	}

	

	public ApplicationTracesId getId() {
		return id;
	}

	public void setId(ApplicationTracesId id) {
		this.id = id;
	}

	public BigDecimal getLineNumber() {
		return this.lineNumber;
	}

	public void setLineNumber(BigDecimal lineNumber) {
		this.lineNumber = lineNumber;
	}

	public String getActionToTake() {
		return this.actionToTake;
	}

	public void setActionToTake(String actionToTake) {
		this.actionToTake = actionToTake;
	}

	public String getActionAFaire() {
		return this.actionAFaire;
	}

	public void setActionAFaire(String actionAFaire) {
		this.actionAFaire = actionAFaire;
	}

	public String getSystemError() {
		return this.systemError;
	}

	public void setSystemError(String systemError) {
		this.systemError = systemError;
	}

	public String getPackageName() {
		return this.packageName;
	}

	public void setPackageName(String packageName) {
		this.packageName = packageName;
	}

	public String getFunctionName() {
		return this.functionName;
	}

	public void setFunctionName(String functionName) {
		this.functionName = functionName;
	}

	public String getTraceLevel() {
		return this.traceLevel;
	}

	public void setTraceLevel(String traceLevel) {
		this.traceLevel = traceLevel;
	}

	public boolean isLogo_fatal() {
		return logo_fatal;
	}

	public void setLogo_fatal(boolean logo_fatal) {
		this.logo_fatal = logo_fatal;
	}

	public boolean isLogo_warn() {
		return logo_warn;
	}

	public void setLogo_warn(boolean logo_warn) {
		this.logo_warn = logo_warn;
	}

	public boolean isLogo_normal() {
		return logo_normal;
	}

	public void setLogo_normal(boolean logo_normal) {
		this.logo_normal = logo_normal;
	}

	public boolean isAction_en() {
		return action_en;
	}

	public void setAction_en(boolean action_en) {
		this.action_en = action_en;
	}

	public boolean isAction_fr() {
		return action_fr;
	}

	public void setAction_fr(boolean action_fr) {
		this.action_fr = action_fr;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((actionAFaire == null) ? 0 : actionAFaire.hashCode());
		result = prime * result
				+ ((actionToTake == null) ? 0 : actionToTake.hashCode());
		result = prime * result
				+ ((functionName == null) ? 0 : functionName.hashCode());
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		result = prime * result
				+ ((lineNumber == null) ? 0 : lineNumber.hashCode());
		result = prime * result
				+ ((packageName == null) ? 0 : packageName.hashCode());
		result = prime * result
				+ ((systemError == null) ? 0 : systemError.hashCode());
		result = prime * result
				+ ((traceLevel == null) ? 0 : traceLevel.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		final ApplicationTraces other = (ApplicationTraces) obj;
		if (actionAFaire == null) {
			if (other.actionAFaire != null)
				return false;
		} else if (!actionAFaire.equals(other.actionAFaire))
			return false;
		if (actionToTake == null) {
			if (other.actionToTake != null)
				return false;
		} else if (!actionToTake.equals(other.actionToTake))
			return false;
		if (functionName == null) {
			if (other.functionName != null)
				return false;
		} else if (!functionName.equals(other.functionName))
			return false;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		if (lineNumber == null) {
			if (other.lineNumber != null)
				return false;
		} else if (!lineNumber.equals(other.lineNumber))
			return false;
		if (packageName == null) {
			if (other.packageName != null)
				return false;
		} else if (!packageName.equals(other.packageName))
			return false;
		if (systemError == null) {
			if (other.systemError != null)
				return false;
		} else if (!systemError.equals(other.systemError))
			return false;
		if (traceLevel == null) {
			if (other.traceLevel != null)
				return false;
		} else if (!traceLevel.equals(other.traceLevel))
			return false;
		return true;
	}

	
	
	
	

}
