package dao.Hibernate.Model;
/**
 * BankEpsId generated by MyEclipse Persistence Tools
 */

public class Bank implements java.io.Serializable {

	// Fields

	private String bankCode;

	private String wording;

	private String centerCode;

	private String currencyCode;

	private String tvaRate;

	private Long daysBeforeRenew;

	private String address;

	private String countryCode;

	private String zipCode;

	private String cityCode;

	// Constructors

	/** default constructor */
	public Bank() {
	}

	/** full constructor */
	public Bank(String bankCode, String wording, String centerCode,
			String currencyCode, String tvaRate, Long daysBeforeRenew,
			String address, String countryCode, String zipCode, String cityCode) {
		this.bankCode = bankCode;
		this.wording = wording;
		this.centerCode = centerCode;
		this.currencyCode = currencyCode;
		this.tvaRate = tvaRate;
		this.daysBeforeRenew = daysBeforeRenew;
		this.address = address;
		this.countryCode = countryCode;
		this.zipCode = zipCode;
		this.cityCode = cityCode;
	}

	// Property accessors

	public String getBankCode() {
		return this.bankCode;
	}

	public void setBankCode(String bankCode) {
		this.bankCode = bankCode;
	}

	public String getWording() {
		return this.wording;
	}

	public void setWording(String wording) {
		this.wording = wording;
	}

	public String getCenterCode() {
		return this.centerCode;
	}

	public void setCenterCode(String centerCode) {
		this.centerCode = centerCode;
	}

	public String getCurrencyCode() {
		return this.currencyCode;
	}

	public void setCurrencyCode(String currencyCode) {
		this.currencyCode = currencyCode;
	}

	public String getTvaRate() {
		return this.tvaRate;
	}

	public void setTvaRate(String tvaRate) {
		this.tvaRate = tvaRate;
	}

	public Long getDaysBeforeRenew() {
		return this.daysBeforeRenew;
	}

	public void setDaysBeforeRenew(Long daysBeforeRenew) {
		this.daysBeforeRenew = daysBeforeRenew;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getCountryCode() {
		return this.countryCode;
	}

	public void setCountryCode(String countryCode) {
		this.countryCode = countryCode;
	}

	public String getZipCode() {
		return this.zipCode;
	}

	public void setZipCode(String zipCode) {
		this.zipCode = zipCode;
	}

	public String getCityCode() {
		return this.cityCode;
	}

	public void setCityCode(String cityCode) {
		this.cityCode = cityCode;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof Bank))
			return false;
		Bank castOther = (Bank) other;

		return ((this.getBankCode() == castOther.getBankCode()) || (this
				.getBankCode() != null
				&& castOther.getBankCode() != null && this.getBankCode()
				.equals(castOther.getBankCode())))
				&& ((this.getWording() == castOther.getWording()) || (this
						.getWording() != null
						&& castOther.getWording() != null && this.getWording()
						.equals(castOther.getWording())))
				&& ((this.getCenterCode() == castOther.getCenterCode()) || (this
						.getCenterCode() != null
						&& castOther.getCenterCode() != null && this
						.getCenterCode().equals(castOther.getCenterCode())))
				&& ((this.getCurrencyCode() == castOther.getCurrencyCode()) || (this
						.getCurrencyCode() != null
						&& castOther.getCurrencyCode() != null && this
						.getCurrencyCode().equals(castOther.getCurrencyCode())))
				&& ((this.getTvaRate() == castOther.getTvaRate()) || (this
						.getTvaRate() != null
						&& castOther.getTvaRate() != null && this.getTvaRate()
						.equals(castOther.getTvaRate())))
				&& ((this.getDaysBeforeRenew() == castOther
						.getDaysBeforeRenew()) || (this.getDaysBeforeRenew() != null
						&& castOther.getDaysBeforeRenew() != null && this
						.getDaysBeforeRenew().equals(
								castOther.getDaysBeforeRenew())))
				&& ((this.getAddress() == castOther.getAddress()) || (this
						.getAddress() != null
						&& castOther.getAddress() != null && this.getAddress()
						.equals(castOther.getAddress())))
				&& ((this.getCountryCode() == castOther.getCountryCode()) || (this
						.getCountryCode() != null
						&& castOther.getCountryCode() != null && this
						.getCountryCode().equals(castOther.getCountryCode())))
				&& ((this.getZipCode() == castOther.getZipCode()) || (this
						.getZipCode() != null
						&& castOther.getZipCode() != null && this.getZipCode()
						.equals(castOther.getZipCode())))
				&& ((this.getCityCode() == castOther.getCityCode()) || (this
						.getCityCode() != null
						&& castOther.getCityCode() != null && this
						.getCityCode().equals(castOther.getCityCode())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getBankCode() == null ? 0 : this.getBankCode().hashCode());
		result = 37 * result
				+ (getWording() == null ? 0 : this.getWording().hashCode());
		result = 37
				* result
				+ (getCenterCode() == null ? 0 : this.getCenterCode()
						.hashCode());
		result = 37
				* result
				+ (getCurrencyCode() == null ? 0 : this.getCurrencyCode()
						.hashCode());
		result = 37 * result
				+ (getTvaRate() == null ? 0 : this.getTvaRate().hashCode());
		result = 37
				* result
				+ (getDaysBeforeRenew() == null ? 0 : this.getDaysBeforeRenew()
						.hashCode());
		result = 37 * result
				+ (getAddress() == null ? 0 : this.getAddress().hashCode());
		result = 37
				* result
				+ (getCountryCode() == null ? 0 : this.getCountryCode()
						.hashCode());
		result = 37 * result
				+ (getZipCode() == null ? 0 : this.getZipCode().hashCode());
		result = 37 * result
				+ (getCityCode() == null ? 0 : this.getCityCode().hashCode());
		return result;
	}

}