package dao.Hibernate.Model;

// Generated 16 juin 2009 17:00:03 by Hibernate Tools 3.2.2.GA

/**
 * BatchDetailsId generated by hbm2java
 */
public class BatchDetailsId implements java.io.Serializable {

	private String bankCode;
	private String batchCode;
	private String batchGroup;

	public BatchDetailsId() {
	}

	public BatchDetailsId(String bankCode, String batchCode, String batchGroup) {
		this.bankCode = bankCode;
		this.batchCode = batchCode;
		this.batchGroup = batchGroup;
	}

	public String getBankCode() {
		return this.bankCode;
	}

	public void setBankCode(String bankCode) {
		this.bankCode = bankCode;
	}

	public String getBatchCode() {
		return this.batchCode;
	}

	public void setBatchCode(String batchCode) {
		this.batchCode = batchCode;
	}

	public String getBatchGroup() {
		return this.batchGroup;
	}

	public void setBatchGroup(String batchGroup) {
		this.batchGroup = batchGroup;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BatchDetailsId))
			return false;
		BatchDetailsId castOther = (BatchDetailsId) other;

		return ((this.getBankCode() == castOther.getBankCode()) || (this
				.getBankCode() != null
				&& castOther.getBankCode() != null && this.getBankCode()
				.equals(castOther.getBankCode())))
				&& ((this.getBatchCode() == castOther.getBatchCode()) || (this
						.getBatchCode() != null
						&& castOther.getBatchCode() != null && this
						.getBatchCode().equals(castOther.getBatchCode())))
				&& ((this.getBatchGroup() == castOther.getBatchGroup()) || (this
						.getBatchGroup() != null
						&& castOther.getBatchGroup() != null && this
						.getBatchGroup().equals(castOther.getBatchGroup())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getBankCode() == null ? 0 : this.getBankCode().hashCode());
		result = 37 * result
				+ (getBatchCode() == null ? 0 : this.getBatchCode().hashCode());
		result = 37
				* result
				+ (getBatchGroup() == null ? 0 : this.getBatchGroup()
						.hashCode());
		return result;
	}

}
