package dao.Hibernate.Model;
// Generated 11 juin 2009 15:07:25 by Hibernate Tools 3.2.2.GA

/**
 * BatchGroup generated by hbm2java
 */
public class BatchGroup implements java.io.Serializable {

	private BatchGroupId id;
	private String batchGroupName;

	public BatchGroup() {
	}

	public BatchGroup(BatchGroupId id, String batchGroupName) {
		this.id = id;
		this.batchGroupName = batchGroupName;
	}

	public BatchGroupId getId() {
		return this.id;
	}

	public void setId(BatchGroupId id) {
		this.id = id;
	}
	
	public String getBatchGroupName() {
		return this.batchGroupName;
	}

	public void setBatchGroupName(String batchGroupName) {
		this.batchGroupName = batchGroupName;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BatchGroup))
			return false;
		BatchGroup castOther = (BatchGroup) other;

		return ((this.getId() == castOther.getId()) || (this
				.getId() != null
				&& castOther.getId() != null && this.getId()
				.equals(castOther.getId())))
				&& ((this.getBatchGroupName() == castOther.getBatchGroupName()) || (this
						.getBatchGroupName() != null
						&& castOther.getBatchGroupName() != null && this
						.getBatchGroupName().equals(
								castOther.getBatchGroupName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getId() == null ? 0 : this.getId().hashCode());
		result = 37
				* result
				+ (getBatchGroupName() == null ? 0 : this.getBatchGroupName()
						.hashCode());
		return result;
	}


}
