package dao.Hibernate.Model;

// Generated 11 juin 2009 15:07:25 by Hibernate Tools 3.2.2.GA

/**
 * BatchGroupId generated by hbm2java
 */
public class BatchGroupId implements java.io.Serializable {

	private String bankCode;
	private String batchGroupCode;

	public BatchGroupId() {
	}

	public BatchGroupId(String bankCode, String batchGroupCode) {
		this.bankCode = bankCode;
		this.batchGroupCode = batchGroupCode;
	}

	public String getBankCode() {
		return this.bankCode;
	}

	public void setBankCode(String bankCode) {
		this.bankCode = bankCode;
	}

	public String getBatchGroupCode() {
		return this.batchGroupCode;
	}

	public void setBatchGroupCode(String batchGroupCode) {
		this.batchGroupCode = batchGroupCode;
	}
}
