package dao.Hibernate.Model;

// Generated 16 juin 2009 17:00:03 by Hibernate Tools 3.2.2.GA

import java.util.Date;

/**
 * BatchDetails generated by hbm2java
 */
public class BatchDetails implements java.io.Serializable {

	private BatchDetailsId id;
	private String batchName;
	private String parameter1;
	private Character typeParameter1;
	private String typeDateParameter1;
	private String parameter2;
	private Character typeParameter2;
	private String typeDateParameter2;
	private String parameter3;
	private Character typeParameter3;
	private String typeDateParameter3;
	private String parameter4;
	private Character typeParameter4;
	private String typeDateParameter4;
	private String parameter5;
	private Character typeParameter5;
	private String typeDateParameter5;
	private String parameter6;
	private Character typeParameter6;
	private String typeDateParameter6;
	private String parameter7;
	private Character typeParameter7;
	private String typeDateParameter7;
	private String parameter8;
	private Character typeParameter8;
	private String typeDateParameter8;
	private String procedureNameToCall;
	private String parameterValue1;
	private String parameterValue2;
	private String parameterValue3;
	private String parameterValue4;
	private String parameterValue5;
	private String parameterValue6;
	private String parameterValue7;
	private String parameterValue8;
	private Date businessDate;
	private Date startDate;
	private Date endDate;
	private Character toBeListed;
	private Short sequenceRuning;
	private Character parallelRunProcessing;
	private Character status;
	private Byte numberOfJobs;
	private Byte numberOfParams;

	public BatchDetails() {
	}

	public BatchDetails(BatchDetailsId id) {
		this.id = id;
	}

	public BatchDetails(BatchDetailsId id, String batchName, String parameter1,
			Character typeParameter1, String typeDateParameter1,
			String parameter2, Character typeParameter2,
			String typeDateParameter2, String parameter3,
			Character typeParameter3, String typeDateParameter3,
			String parameter4, Character typeParameter4,
			String typeDateParameter4, String parameter5,
			Character typeParameter5, String typeDateParameter5,
			String parameter6, Character typeParameter6,
			String typeDateParameter6, String parameter7,
			Character typeParameter7, String typeDateParameter7,
			String parameter8, Character typeParameter8,
			String typeDateParameter8, String procedureNameToCall,
			String parameterValue1, String parameterValue2,
			String parameterValue3, String parameterValue4,
			String parameterValue5, String parameterValue6,
			String parameterValue7, String parameterValue8, Date businessDate,
			Date startDate, Date endDate, Character toBeListed,
			Short sequenceRuning, Character parallelRunProcessing,
			Byte numberOfJobs, Byte numberOfParams) {
		this.id = id;
		this.batchName = batchName;
		this.parameter1 = parameter1;
		this.typeParameter1 = typeParameter1;
		this.typeDateParameter1 = typeDateParameter1;
		this.parameter2 = parameter2;
		this.typeParameter2 = typeParameter2;
		this.typeDateParameter2 = typeDateParameter2;
		this.parameter3 = parameter3;
		this.typeParameter3 = typeParameter3;
		this.typeDateParameter3 = typeDateParameter3;
		this.parameter4 = parameter4;
		this.typeParameter4 = typeParameter4;
		this.typeDateParameter4 = typeDateParameter4;
		this.parameter5 = parameter5;
		this.typeParameter5 = typeParameter5;
		this.typeDateParameter5 = typeDateParameter5;
		this.parameter6 = parameter6;
		this.typeParameter6 = typeParameter6;
		this.typeDateParameter6 = typeDateParameter6;
		this.parameter7 = parameter7;
		this.typeParameter7 = typeParameter7;
		this.typeDateParameter7 = typeDateParameter7;
		this.parameter8 = parameter8;
		this.typeParameter8 = typeParameter8;
		this.typeDateParameter8 = typeDateParameter8;
		this.procedureNameToCall = procedureNameToCall;
		this.parameterValue1 = parameterValue1;
		this.parameterValue2 = parameterValue2;
		this.parameterValue3 = parameterValue3;
		this.parameterValue4 = parameterValue4;
		this.parameterValue5 = parameterValue5;
		this.parameterValue6 = parameterValue6;
		this.parameterValue7 = parameterValue7;
		this.parameterValue8 = parameterValue8;
		this.businessDate = businessDate;
		this.startDate = startDate;
		this.endDate = endDate;
		this.toBeListed = toBeListed;
		this.sequenceRuning = sequenceRuning;
		this.parallelRunProcessing = parallelRunProcessing;
		this.numberOfJobs = numberOfJobs;
		this.numberOfParams = numberOfParams;
	}

	public BatchDetailsId getId() {
		return this.id;
	}

	public void setId(BatchDetailsId id) {
		this.id = id;
	}

	public String getBatchName() {
		return this.batchName;
	}

	public void setBatchName(String batchName) {
		this.batchName = batchName;
	}

	public String getParameter1() {
		return this.parameter1;
	}

	public void setParameter1(String parameter1) {
		this.parameter1 = parameter1;
	}

	public Character getTypeParameter1() {
		return this.typeParameter1;
	}

	public void setTypeParameter1(Character typeParameter1) {
		this.typeParameter1 = typeParameter1;
	}

	public String getTypeDateParameter1() {
		return this.typeDateParameter1;
	}

	public void setTypeDateParameter1(String typeDateParameter1) {
		this.typeDateParameter1 = typeDateParameter1;
	}

	public String getParameter2() {
		return this.parameter2;
	}

	public void setParameter2(String parameter2) {
		this.parameter2 = parameter2;
	}

	public Character getTypeParameter2() {
		return this.typeParameter2;
	}

	public void setTypeParameter2(Character typeParameter2) {
		this.typeParameter2 = typeParameter2;
	}

	public String getTypeDateParameter2() {
		return this.typeDateParameter2;
	}

	public void setTypeDateParameter2(String typeDateParameter2) {
		this.typeDateParameter2 = typeDateParameter2;
	}

	public String getParameter3() {
		return this.parameter3;
	}

	public void setParameter3(String parameter3) {
		this.parameter3 = parameter3;
	}

	public Character getTypeParameter3() {
		return this.typeParameter3;
	}

	public void setTypeParameter3(Character typeParameter3) {
		this.typeParameter3 = typeParameter3;
	}

	public String getTypeDateParameter3() {
		return this.typeDateParameter3;
	}

	public void setTypeDateParameter3(String typeDateParameter3) {
		this.typeDateParameter3 = typeDateParameter3;
	}

	public String getParameter4() {
		return this.parameter4;
	}

	public void setParameter4(String parameter4) {
		this.parameter4 = parameter4;
	}

	public Character getTypeParameter4() {
		return this.typeParameter4;
	}

	public void setTypeParameter4(Character typeParameter4) {
		this.typeParameter4 = typeParameter4;
	}

	public String getTypeDateParameter4() {
		return this.typeDateParameter4;
	}

	public void setTypeDateParameter4(String typeDateParameter4) {
		this.typeDateParameter4 = typeDateParameter4;
	}

	public String getParameter5() {
		return this.parameter5;
	}

	public void setParameter5(String parameter5) {
		this.parameter5 = parameter5;
	}

	public Character getTypeParameter5() {
		return this.typeParameter5;
	}

	public void setTypeParameter5(Character typeParameter5) {
		this.typeParameter5 = typeParameter5;
	}

	public String getTypeDateParameter5() {
		return this.typeDateParameter5;
	}

	public void setTypeDateParameter5(String typeDateParameter5) {
		this.typeDateParameter5 = typeDateParameter5;
	}

	public String getParameter6() {
		return this.parameter6;
	}

	public void setParameter6(String parameter6) {
		this.parameter6 = parameter6;
	}

	public Character getTypeParameter6() {
		return this.typeParameter6;
	}

	public void setTypeParameter6(Character typeParameter6) {
		this.typeParameter6 = typeParameter6;
	}

	public String getTypeDateParameter6() {
		return this.typeDateParameter6;
	}

	public void setTypeDateParameter6(String typeDateParameter6) {
		this.typeDateParameter6 = typeDateParameter6;
	}

	public String getParameter7() {
		return this.parameter7;
	}

	public void setParameter7(String parameter7) {
		this.parameter7 = parameter7;
	}

	public Character getTypeParameter7() {
		return this.typeParameter7;
	}

	public void setTypeParameter7(Character typeParameter7) {
		this.typeParameter7 = typeParameter7;
	}

	public String getTypeDateParameter7() {
		return this.typeDateParameter7;
	}

	public void setTypeDateParameter7(String typeDateParameter7) {
		this.typeDateParameter7 = typeDateParameter7;
	}

	public String getParameter8() {
		return this.parameter8;
	}

	public void setParameter8(String parameter8) {
		this.parameter8 = parameter8;
	}

	public Character getTypeParameter8() {
		return this.typeParameter8;
	}

	public void setTypeParameter8(Character typeParameter8) {
		this.typeParameter8 = typeParameter8;
	}

	public String getTypeDateParameter8() {
		return this.typeDateParameter8;
	}

	public void setTypeDateParameter8(String typeDateParameter8) {
		this.typeDateParameter8 = typeDateParameter8;
	}

	public String getProcedureNameToCall() {
		return this.procedureNameToCall;
	}

	public void setProcedureNameToCall(String procedureNameToCall) {
		this.procedureNameToCall = procedureNameToCall;
	}

	public String getParameterValue1() {
		return this.parameterValue1;
	}

	public void setParameterValue1(String parameterValue1) {
		this.parameterValue1 = parameterValue1;
	}

	public String getParameterValue2() {
		return this.parameterValue2;
	}

	public void setParameterValue2(String parameterValue2) {
		this.parameterValue2 = parameterValue2;
	}

	public String getParameterValue3() {
		return this.parameterValue3;
	}

	public void setParameterValue3(String parameterValue3) {
		this.parameterValue3 = parameterValue3;
	}

	public String getParameterValue4() {
		return this.parameterValue4;
	}

	public void setParameterValue4(String parameterValue4) {
		this.parameterValue4 = parameterValue4;
	}

	public String getParameterValue5() {
		return this.parameterValue5;
	}

	public void setParameterValue5(String parameterValue5) {
		this.parameterValue5 = parameterValue5;
	}

	public String getParameterValue6() {
		return this.parameterValue6;
	}

	public void setParameterValue6(String parameterValue6) {
		this.parameterValue6 = parameterValue6;
	}

	public String getParameterValue7() {
		return this.parameterValue7;
	}

	public void setParameterValue7(String parameterValue7) {
		this.parameterValue7 = parameterValue7;
	}

	public String getParameterValue8() {
		return this.parameterValue8;
	}

	public void setParameterValue8(String parameterValue8) {
		this.parameterValue8 = parameterValue8;
	}

	public Date getBusinessDate() {
		return this.businessDate;
	}

	public void setBusinessDate(Date businessDate) {
		this.businessDate = businessDate;
	}

	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public Character getToBeListed() {
		return this.toBeListed;
	}

	public void setToBeListed(Character toBeListed) {
		this.toBeListed = toBeListed;
	}

	public Short getSequenceRuning() {
		return this.sequenceRuning;
	}

	public void setSequenceRuning(Short sequenceRuning) {
		this.sequenceRuning = sequenceRuning;
	}

	public Character getParallelRunProcessing() {
		return this.parallelRunProcessing;
	}

	public void setParallelRunProcessing(Character parallelRunProcessing) {
		this.parallelRunProcessing = parallelRunProcessing;
	}

	public Byte getNumberOfJobs() {
		return this.numberOfJobs;
	}

	public void setNumberOfJobs(Byte numberOfJobs) {
		this.numberOfJobs = numberOfJobs;
	}

	public Byte getNumberOfParams() {
		return this.numberOfParams;
	}

	public void setNumberOfParams(Byte numberOfParams) {
		this.numberOfParams = numberOfParams;
	}

	public Character getStatus() {
		return status;
	}

	public void setStatus(Character status) {
		this.status = status;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((batchName == null) ? 0 : batchName.hashCode());
		result = prime * result
				+ ((businessDate == null) ? 0 : businessDate.hashCode());
		result = prime * result + ((endDate == null) ? 0 : endDate.hashCode());
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		result = prime * result
				+ ((numberOfJobs == null) ? 0 : numberOfJobs.hashCode());
		result = prime * result
				+ ((numberOfParams == null) ? 0 : numberOfParams.hashCode());
		result = prime
				* result
				+ ((parallelRunProcessing == null) ? 0 : parallelRunProcessing
						.hashCode());
		result = prime * result
				+ ((parameter1 == null) ? 0 : parameter1.hashCode());
		result = prime * result
				+ ((parameter2 == null) ? 0 : parameter2.hashCode());
		result = prime * result
				+ ((parameter3 == null) ? 0 : parameter3.hashCode());
		result = prime * result
				+ ((parameter4 == null) ? 0 : parameter4.hashCode());
		result = prime * result
				+ ((parameter5 == null) ? 0 : parameter5.hashCode());
		result = prime * result
				+ ((parameter6 == null) ? 0 : parameter6.hashCode());
		result = prime * result
				+ ((parameter7 == null) ? 0 : parameter7.hashCode());
		result = prime * result
				+ ((parameter8 == null) ? 0 : parameter8.hashCode());
		result = prime * result
				+ ((parameterValue1 == null) ? 0 : parameterValue1.hashCode());
		result = prime * result
				+ ((parameterValue2 == null) ? 0 : parameterValue2.hashCode());
		result = prime * result
				+ ((parameterValue3 == null) ? 0 : parameterValue3.hashCode());
		result = prime * result
				+ ((parameterValue4 == null) ? 0 : parameterValue4.hashCode());
		result = prime * result
				+ ((parameterValue5 == null) ? 0 : parameterValue5.hashCode());
		result = prime * result
				+ ((parameterValue6 == null) ? 0 : parameterValue6.hashCode());
		result = prime * result
				+ ((parameterValue7 == null) ? 0 : parameterValue7.hashCode());
		result = prime * result
				+ ((parameterValue8 == null) ? 0 : parameterValue8.hashCode());
		result = prime
				* result
				+ ((procedureNameToCall == null) ? 0 : procedureNameToCall
						.hashCode());
		result = prime * result
				+ ((sequenceRuning == null) ? 0 : sequenceRuning.hashCode());
		result = prime * result
				+ ((startDate == null) ? 0 : startDate.hashCode());
		result = prime * result + ((status == null) ? 0 : status.hashCode());
		result = prime * result
				+ ((toBeListed == null) ? 0 : toBeListed.hashCode());
		result = prime
				* result
				+ ((typeDateParameter1 == null) ? 0 : typeDateParameter1
						.hashCode());
		result = prime
				* result
				+ ((typeDateParameter2 == null) ? 0 : typeDateParameter2
						.hashCode());
		result = prime
				* result
				+ ((typeDateParameter3 == null) ? 0 : typeDateParameter3
						.hashCode());
		result = prime
				* result
				+ ((typeDateParameter4 == null) ? 0 : typeDateParameter4
						.hashCode());
		result = prime
				* result
				+ ((typeDateParameter5 == null) ? 0 : typeDateParameter5
						.hashCode());
		result = prime
				* result
				+ ((typeDateParameter6 == null) ? 0 : typeDateParameter6
						.hashCode());
		result = prime
				* result
				+ ((typeDateParameter7 == null) ? 0 : typeDateParameter7
						.hashCode());
		result = prime
				* result
				+ ((typeDateParameter8 == null) ? 0 : typeDateParameter8
						.hashCode());
		result = prime * result
				+ ((typeParameter1 == null) ? 0 : typeParameter1.hashCode());
		result = prime * result
				+ ((typeParameter2 == null) ? 0 : typeParameter2.hashCode());
		result = prime * result
				+ ((typeParameter3 == null) ? 0 : typeParameter3.hashCode());
		result = prime * result
				+ ((typeParameter4 == null) ? 0 : typeParameter4.hashCode());
		result = prime * result
				+ ((typeParameter5 == null) ? 0 : typeParameter5.hashCode());
		result = prime * result
				+ ((typeParameter6 == null) ? 0 : typeParameter6.hashCode());
		result = prime * result
				+ ((typeParameter7 == null) ? 0 : typeParameter7.hashCode());
		result = prime * result
				+ ((typeParameter8 == null) ? 0 : typeParameter8.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		final BatchDetails other = (BatchDetails) obj;
		if (batchName == null) {
			if (other.batchName != null)
				return false;
		} else if (!batchName.equals(other.batchName))
			return false;
		if (businessDate == null) {
			if (other.businessDate != null)
				return false;
		} else if (!businessDate.equals(other.businessDate))
			return false;
		if (endDate == null) {
			if (other.endDate != null)
				return false;
		} else if (!endDate.equals(other.endDate))
			return false;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		if (numberOfJobs == null) {
			if (other.numberOfJobs != null)
				return false;
		} else if (!numberOfJobs.equals(other.numberOfJobs))
			return false;
		if (numberOfParams == null) {
			if (other.numberOfParams != null)
				return false;
		} else if (!numberOfParams.equals(other.numberOfParams))
			return false;
		if (parallelRunProcessing == null) {
			if (other.parallelRunProcessing != null)
				return false;
		} else if (!parallelRunProcessing.equals(other.parallelRunProcessing))
			return false;
		if (parameter1 == null) {
			if (other.parameter1 != null)
				return false;
		} else if (!parameter1.equals(other.parameter1))
			return false;
		if (parameter2 == null) {
			if (other.parameter2 != null)
				return false;
		} else if (!parameter2.equals(other.parameter2))
			return false;
		if (parameter3 == null) {
			if (other.parameter3 != null)
				return false;
		} else if (!parameter3.equals(other.parameter3))
			return false;
		if (parameter4 == null) {
			if (other.parameter4 != null)
				return false;
		} else if (!parameter4.equals(other.parameter4))
			return false;
		if (parameter5 == null) {
			if (other.parameter5 != null)
				return false;
		} else if (!parameter5.equals(other.parameter5))
			return false;
		if (parameter6 == null) {
			if (other.parameter6 != null)
				return false;
		} else if (!parameter6.equals(other.parameter6))
			return false;
		if (parameter7 == null) {
			if (other.parameter7 != null)
				return false;
		} else if (!parameter7.equals(other.parameter7))
			return false;
		if (parameter8 == null) {
			if (other.parameter8 != null)
				return false;
		} else if (!parameter8.equals(other.parameter8))
			return false;
		if (parameterValue1 == null) {
			if (other.parameterValue1 != null)
				return false;
		} else if (!parameterValue1.equals(other.parameterValue1))
			return false;
		if (parameterValue2 == null) {
			if (other.parameterValue2 != null)
				return false;
		} else if (!parameterValue2.equals(other.parameterValue2))
			return false;
		if (parameterValue3 == null) {
			if (other.parameterValue3 != null)
				return false;
		} else if (!parameterValue3.equals(other.parameterValue3))
			return false;
		if (parameterValue4 == null) {
			if (other.parameterValue4 != null)
				return false;
		} else if (!parameterValue4.equals(other.parameterValue4))
			return false;
		if (parameterValue5 == null) {
			if (other.parameterValue5 != null)
				return false;
		} else if (!parameterValue5.equals(other.parameterValue5))
			return false;
		if (parameterValue6 == null) {
			if (other.parameterValue6 != null)
				return false;
		} else if (!parameterValue6.equals(other.parameterValue6))
			return false;
		if (parameterValue7 == null) {
			if (other.parameterValue7 != null)
				return false;
		} else if (!parameterValue7.equals(other.parameterValue7))
			return false;
		if (parameterValue8 == null) {
			if (other.parameterValue8 != null)
				return false;
		} else if (!parameterValue8.equals(other.parameterValue8))
			return false;
		if (procedureNameToCall == null) {
			if (other.procedureNameToCall != null)
				return false;
		} else if (!procedureNameToCall.equals(other.procedureNameToCall))
			return false;
		if (sequenceRuning == null) {
			if (other.sequenceRuning != null)
				return false;
		} else if (!sequenceRuning.equals(other.sequenceRuning))
			return false;
		if (startDate == null) {
			if (other.startDate != null)
				return false;
		} else if (!startDate.equals(other.startDate))
			return false;
		if (status == null) {
			if (other.status != null)
				return false;
		} else if (!status.equals(other.status))
			return false;
		if (toBeListed == null) {
			if (other.toBeListed != null)
				return false;
		} else if (!toBeListed.equals(other.toBeListed))
			return false;
		if (typeDateParameter1 == null) {
			if (other.typeDateParameter1 != null)
				return false;
		} else if (!typeDateParameter1.equals(other.typeDateParameter1))
			return false;
		if (typeDateParameter2 == null) {
			if (other.typeDateParameter2 != null)
				return false;
		} else if (!typeDateParameter2.equals(other.typeDateParameter2))
			return false;
		if (typeDateParameter3 == null) {
			if (other.typeDateParameter3 != null)
				return false;
		} else if (!typeDateParameter3.equals(other.typeDateParameter3))
			return false;
		if (typeDateParameter4 == null) {
			if (other.typeDateParameter4 != null)
				return false;
		} else if (!typeDateParameter4.equals(other.typeDateParameter4))
			return false;
		if (typeDateParameter5 == null) {
			if (other.typeDateParameter5 != null)
				return false;
		} else if (!typeDateParameter5.equals(other.typeDateParameter5))
			return false;
		if (typeDateParameter6 == null) {
			if (other.typeDateParameter6 != null)
				return false;
		} else if (!typeDateParameter6.equals(other.typeDateParameter6))
			return false;
		if (typeDateParameter7 == null) {
			if (other.typeDateParameter7 != null)
				return false;
		} else if (!typeDateParameter7.equals(other.typeDateParameter7))
			return false;
		if (typeDateParameter8 == null) {
			if (other.typeDateParameter8 != null)
				return false;
		} else if (!typeDateParameter8.equals(other.typeDateParameter8))
			return false;
		if (typeParameter1 == null) {
			if (other.typeParameter1 != null)
				return false;
		} else if (!typeParameter1.equals(other.typeParameter1))
			return false;
		if (typeParameter2 == null) {
			if (other.typeParameter2 != null)
				return false;
		} else if (!typeParameter2.equals(other.typeParameter2))
			return false;
		if (typeParameter3 == null) {
			if (other.typeParameter3 != null)
				return false;
		} else if (!typeParameter3.equals(other.typeParameter3))
			return false;
		if (typeParameter4 == null) {
			if (other.typeParameter4 != null)
				return false;
		} else if (!typeParameter4.equals(other.typeParameter4))
			return false;
		if (typeParameter5 == null) {
			if (other.typeParameter5 != null)
				return false;
		} else if (!typeParameter5.equals(other.typeParameter5))
			return false;
		if (typeParameter6 == null) {
			if (other.typeParameter6 != null)
				return false;
		} else if (!typeParameter6.equals(other.typeParameter6))
			return false;
		if (typeParameter7 == null) {
			if (other.typeParameter7 != null)
				return false;
		} else if (!typeParameter7.equals(other.typeParameter7))
			return false;
		if (typeParameter8 == null) {
			if (other.typeParameter8 != null)
				return false;
		} else if (!typeParameter8.equals(other.typeParameter8))
			return false;
		return true;
	}
	
	

}
