package dao.Hibernate.Model;
// Generated 7 avr. 2010 10:56:27 by Hibernate Tools 3.2.2.GA

/**
 * BlackListCountry generated by hbm2java
 */
public class BlackListCountry implements java.io.Serializable {

	private String countryCode;
	private String wording;

	public BlackListCountry() {
	}

	public BlackListCountry(String countryCode) {
		this.countryCode = countryCode;
	}

	public BlackListCountry(String countryCode, String wording) {
		this.countryCode = countryCode;
		this.wording = wording;
	}

	public String getCountryCode() {
		return this.countryCode;
	}

	public void setCountryCode(String countryCode) {
		this.countryCode = countryCode;
	}

	public String getWording() {
		return this.wording;
	}

	public void setWording(String wording) {
		this.wording = wording;
	}

}
