package dao.Hibernate.Model;

// Generated 18 août 2009 10:35:50 by Hibernate Tools 3.2.2.GA

import java.math.BigDecimal;


/**
 * Branch generated by hbm2java
 */
public class Branch implements java.io.Serializable {

	private BranchId id;
	private String cityCode;
	private String countryCode;
	private String wording;
	private BigDecimal daysBeforeRenew;
	private String bankLocation;
	private String address;
	private String zipCode;

	public Branch() {
	}

	public Branch(BranchId id) {
		this.id = id;
	}

	public Branch(BranchId id, String cityCode, String countryCode,
			String wording, BigDecimal daysBeforeRenew, String bankLocation,
			String address, String zipCode) {
		this.id = id;
		this.cityCode = cityCode;
		this.countryCode = countryCode;
		this.wording = wording;
		this.daysBeforeRenew = daysBeforeRenew;
		this.bankLocation = bankLocation;
		this.address = address;
		this.zipCode = zipCode;
	}

	public BranchId getId() {
		return this.id;
	}

	public void setId(BranchId id) {
		this.id = id;
	}

	public String getCityCode() {
		return this.cityCode;
	}

	public void setCityCode(String cityCode) {
		this.cityCode = cityCode;
	}

	public String getCountryCode() {
		return this.countryCode;
	}

	public void setCountryCode(String countryCode) {
		this.countryCode = countryCode;
	}

	public String getWording() {
		return this.wording;
	}

	public void setWording(String wording) {
		this.wording = wording;
	}

	public BigDecimal getDaysBeforeRenew() {
		return this.daysBeforeRenew;
	}

	public void setDaysBeforeRenew(BigDecimal daysBeforeRenew) {
		this.daysBeforeRenew = daysBeforeRenew;
	}

	public String getBankLocation() {
		return this.bankLocation;
	}

	public void setBankLocation(String bankLocation) {
		this.bankLocation = bankLocation;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getZipCode() {
		return this.zipCode;
	}

	public void setZipCode(String zipCode) {
		this.zipCode = zipCode;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((address == null) ? 0 : address.hashCode());
		result = prime * result
				+ ((bankLocation == null) ? 0 : bankLocation.hashCode());
		result = prime * result
				+ ((cityCode == null) ? 0 : cityCode.hashCode());
		result = prime * result
				+ ((countryCode == null) ? 0 : countryCode.hashCode());
		result = prime * result
				+ ((daysBeforeRenew == null) ? 0 : daysBeforeRenew.hashCode());
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		result = prime * result + ((wording == null) ? 0 : wording.hashCode());
		result = prime * result + ((zipCode == null) ? 0 : zipCode.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		final Branch other = (Branch) obj;
		if (address == null) {
			if (other.address != null)
				return false;
		} else if (!address.equals(other.address))
			return false;
		if (bankLocation == null) {
			if (other.bankLocation != null)
				return false;
		} else if (!bankLocation.equals(other.bankLocation))
			return false;
		if (cityCode == null) {
			if (other.cityCode != null)
				return false;
		} else if (!cityCode.equals(other.cityCode))
			return false;
		if (countryCode == null) {
			if (other.countryCode != null)
				return false;
		} else if (!countryCode.equals(other.countryCode))
			return false;
		if (daysBeforeRenew == null) {
			if (other.daysBeforeRenew != null)
				return false;
		} else if (!daysBeforeRenew.equals(other.daysBeforeRenew))
			return false;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		if (wording == null) {
			if (other.wording != null)
				return false;
		} else if (!wording.equals(other.wording))
			return false;
		if (zipCode == null) {
			if (other.zipCode != null)
				return false;
		} else if (!zipCode.equals(other.zipCode))
			return false;
		return true;
	}
	

}
