package dao.Hibernate.Model;

// Generated 18 août 2009 10:35:50 by Hibernate Tools 3.2.2.GA

/**
 * BranchId generated by hbm2java
 */
public class BranchId implements java.io.Serializable {

	private String bankCode;
	private String branchCode;

	public BranchId() {
	}

	public BranchId(String bankCode, String branchCode) {
		this.bankCode = bankCode;
		this.branchCode = branchCode;
	}

	public String getBankCode() {
		return this.bankCode;
	}

	public void setBankCode(String bankCode) {
		this.bankCode = bankCode;
	}

	public String getBranchCode() {
		return this.branchCode;
	}

	public void setBranchCode(String branchCode) {
		this.branchCode = branchCode;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BranchId))
			return false;
		BranchId castOther = (BranchId) other;

		return ((this.getBankCode() == castOther.getBankCode()) || (this
				.getBankCode() != null
				&& castOther.getBankCode() != null && this.getBankCode()
				.equals(castOther.getBankCode())))
				&& ((this.getBranchCode() == castOther.getBranchCode()) || (this
						.getBranchCode() != null
						&& castOther.getBranchCode() != null && this
						.getBranchCode().equals(castOther.getBranchCode())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getBankCode() == null ? 0 : this.getBankCode().hashCode());
		result = 37
				* result
				+ (getBranchCode() == null ? 0 : this.getBranchCode()
						.hashCode());
		return result;
	}

}
