package dao.Hibernate.Model;
// Generated 25 janv. 2010 12:46:34 by Hibernate Tools 3.2.2.GA

/**
 * Center generated by hbm2java
 */
public class Center implements java.io.Serializable {

	private String centerCode;
	private String wording;
	private String centerType;

	public Center() {
	}

	public Center(String centerCode) {
		this.centerCode = centerCode;
	}

	public Center(String centerCode, String wording, String centerType) {
		this.centerCode = centerCode;
		this.wording = wording;
		this.centerType = centerType;
	}

	public String getCenterCode() {
		return this.centerCode;
	}

	public void setCenterCode(String centerCode) {
		this.centerCode = centerCode;
	}

	public String getWording() {
		return this.wording;
	}

	public void setWording(String wording) {
		this.wording = wording;
	}

	public String getCenterType() {
		return this.centerType;
	}

	public void setCenterType(String centerType) {
		this.centerType = centerType;
	}

}
