package dao.Hibernate.Model;

// Generated 1 avr. 2010 12:50:45 by Hibernate Tools 3.2.2.GA

/**
 * ConditionMonitoring generated by hbm2java
 */
public class ConditionMonitoring implements java.io.Serializable {

	private String conditionCode;
	private String wording;

	public ConditionMonitoring() {
	}

	public ConditionMonitoring(String conditionCode) {
		this.conditionCode = conditionCode;
	}

	public ConditionMonitoring(String conditionCode, String wording) {
		this.conditionCode = conditionCode;
		this.wording = wording;
	}

	public String getConditionCode() {
		return this.conditionCode;
	}

	public void setConditionCode(String conditionCode) {
		this.conditionCode = conditionCode;
	}

	public String getWording() {
		return this.wording;
	}

	public void setWording(String wording) {
		this.wording = wording;
	}

}
