package dao.Hibernate.Model;

// default package
// Generated 7 avr. 2010 17:19:09 by Hibernate Tools 3.2.2.GA

import java.math.BigDecimal;

/**
 * CustomerAccount generated by hbm2java
 */
public class CustomerAccount implements java.io.Serializable {

	private String accountNumber;
	private BigDecimal balance;

	public CustomerAccount() {
	}

	public CustomerAccount(String accountNumber) {
		this.accountNumber = accountNumber;
	}

	public CustomerAccount(String accountNumber, BigDecimal balance) {
		this.accountNumber = accountNumber;
		this.balance = balance;
	}

	public String getAccountNumber() {
		return this.accountNumber;
	}

	public void setAccountNumber(String accountNumber) {
		this.accountNumber = accountNumber;
	}

	public BigDecimal getBalance() {
		return this.balance;
	}

	public void setBalance(BigDecimal balance) {
		this.balance = balance;
	}

}
