package dao.Hibernate.Model;
// default package
// Generated 7 sept. 2009 09:59:04 by Hibernate Tools 3.2.2.GA

/**
 * EpsAdministrationMessageId generated by hbm2java
 */
public class EpsAdministrationMessageId implements java.io.Serializable {

	private String userCode;
	private short messageNumber;
	private String subject;

	public EpsAdministrationMessageId() {
	}

	public EpsAdministrationMessageId(String userCode, short messageNumber,
			String subject) {
		this.userCode = userCode;
		this.messageNumber = messageNumber;
		this.subject = subject;
	}

	public String getUserCode() {
		return this.userCode;
	}

	public void setUserCode(String userCode) {
		this.userCode = userCode;
	}

	public short getMessageNumber() {
		return this.messageNumber;
	}

	public void setMessageNumber(short messageNumber) {
		this.messageNumber = messageNumber;
	}

	public String getSubject() {
		return this.subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EpsAdministrationMessageId))
			return false;
		EpsAdministrationMessageId castOther = (EpsAdministrationMessageId) other;

		return ((this.getUserCode() == castOther.getUserCode()) || (this
				.getUserCode() != null
				&& castOther.getUserCode() != null && this.getUserCode()
				.equals(castOther.getUserCode())))
				&& (this.getMessageNumber() == castOther.getMessageNumber())
				&& ((this.getSubject() == castOther.getSubject()) || (this
						.getSubject() != null
						&& castOther.getSubject() != null && this.getSubject()
						.equals(castOther.getSubject())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getUserCode() == null ? 0 : this.getUserCode().hashCode());
		result = 37 * result + this.getMessageNumber();
		result = 37 * result
				+ (getSubject() == null ? 0 : this.getSubject().hashCode());
		return result;
	}

}
