package dao.Hibernate.Model;
// default package
// Generated 7 sept. 2009 09:59:04 by Hibernate Tools 3.2.2.GA

import java.text.SimpleDateFormat;
import java.util.Date;


/**
 * EpsAdministrationMessage generated by hbm2java
 */
public class EpsAdministrationMessage implements java.io.Serializable {

	private EpsAdministrationMessageId id;
	private String details;
	private Character priority;
	private Date messageDate;
	private String libelle;
	private String libelleDate;
	public EpsAdministrationMessage() {
	}

	public EpsAdministrationMessage(EpsAdministrationMessageId id) {
		this.id = id;
	}

	public EpsAdministrationMessage(EpsAdministrationMessageId id,
			String details, Character priority, Date messageDate) {
		this.id = id;
		this.details = details;
		this.priority = priority;
		this.messageDate = messageDate;
	}

	public EpsAdministrationMessageId getId() {
		return this.id;
	}

	public void setId(EpsAdministrationMessageId id) {
		this.id = id;
	}

	public String getDetails() {
		return this.details;
	}

	public void setDetails(String details) {
		this.details = details;
	}

	public Character getPriority() {
		return this.priority;
	}

	public void setPriority(Character priority) {
		this.priority = priority;
	}

	public Date getMessageDate() {
		return this.messageDate;
	}

	public void setMessageDate(Date messageDate) {
		this.messageDate = messageDate;
	}

	public String getLibelle() {
		if (this.getPriority().toString().equals("H")) return("High");
		if (this.getPriority().toString().equals("N")) return("Normal");
		if (this.getPriority().toString().equals("L")) return("Low");
		else return ("");
	}

	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}
	public String getLibelleDate() {
		if(getMessageDate() != null){
		SimpleDateFormat simpleFormat = new SimpleDateFormat("dd/MM/yyyy");
		libelleDate = simpleFormat.format(getMessageDate());
		}
		return libelleDate;
	}

	public void setLibelleDate(String libelleDate) {
		this.libelleDate = libelleDate;
	}

}
