package dao.Hibernate.Model;

import java.util.HashSet;
import java.util.Set;

/**
 * EpsHabilitationParam generated by MyEclipse Persistence Tools
 */

public class EpsHabilitationParam implements java.io.Serializable {

	// Fields

	private String code;

	private String libelle;

	private Set<UserHabilitationParam> userHabilitationParams = new HashSet<UserHabilitationParam>(0);

	// Constructors

	/** default constructor */
	public EpsHabilitationParam() {
	}

	/** minimal constructor */
	public EpsHabilitationParam(String code, String libelle) {
		this.code = code;
		this.libelle = libelle;
	}

	/** full constructor */
	public EpsHabilitationParam(String code, String libelle,
			Set userHabilitationParams) {
		this.code = code;
		this.libelle = libelle;
		this.userHabilitationParams = userHabilitationParams;
	}

	// Property accessors

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getLibelle() {
		return this.libelle;
	}

	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

	public Set getUserHabilitationParams() {
		return this.userHabilitationParams;
	}

	public void setUserHabilitationParams(Set userHabilitationParams) {
		this.userHabilitationParams = userHabilitationParams;
	}

}