package dao.Hibernate.Model;
// default package
// Generated 3 sept. 2009 13:34:26 by Hibernate Tools 3.2.2.GA

import java.text.SimpleDateFormat;
import java.util.Date;


/**
 * EpsMemos generated by hbm2java
 */
public class EpsMemos implements java.io.Serializable {

	private EpsMemosId id;
	private String details;
	private Date executionDate;
	private String libelleDate;

	public EpsMemos() {
	}

	public EpsMemos(EpsMemosId id) {
		this.id = id;
	}

	public EpsMemos(EpsMemosId id, String details, Date executionDate) {
		this.id = id;
		this.details = details;
		this.executionDate = executionDate;
	}

	public EpsMemosId getId() {
		return this.id;
	}

	public void setId(EpsMemosId id) {
		this.id = id;
	}

	public String getDetails() {
		return this.details;
	}

	public void setDetails(String details) {
		this.details = details;
	}

	public Date getExecutionDate() {
		return this.executionDate;
	}

	public void setExecutionDate(Date executionDate) {
		this.executionDate = executionDate;
	}
	public String getLibelleDate() {
		if(getExecutionDate() != null){
		SimpleDateFormat simpleFormat = new SimpleDateFormat("dd/MM/yyyy");
		libelleDate = simpleFormat.format(getExecutionDate());
		}
		return libelleDate;
	}

	public void setLibelleDate(String libelleDate) {
		this.libelleDate = libelleDate;
	}

}
