package dao.Hibernate.Model;
// default package
// Generated 3 sept. 2009 13:34:26 by Hibernate Tools 3.2.2.GA

import java.text.SimpleDateFormat;
import java.util.Date;


/**
 * EpsPlanning generated by hbm2java
 */
public class EpsPlanning implements java.io.Serializable {

	private EpsPlanningId id;
	private Date startDate;
	private Date endDate;
	private String libelleDate;
	private String libelleDate2;

	public EpsPlanning() {
	}

	public EpsPlanning(EpsPlanningId id) {
		this.id = id;
	}

	public EpsPlanning(EpsPlanningId id, Date startDate, Date endDate) {
		this.id = id;
		this.startDate = startDate;
		this.endDate = endDate;
	}

	public EpsPlanningId getId() {
		return this.id;
	}

	public void setId(EpsPlanningId id) {
		this.id = id;
	}

	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}
	public String getLibelleDate() {
		if (getStartDate() != null){
		SimpleDateFormat simpleFormat = new SimpleDateFormat("dd/MM/yyyy");
		libelleDate = simpleFormat.format(getStartDate());
		}
		return libelleDate;
	}

	public void setLibelleDate(String libelleDate) {
		this.libelleDate = libelleDate;
	}

	public String getLibelleDate2() {
		if (getEndDate() != null){
		SimpleDateFormat simpleFormat = new SimpleDateFormat("dd/MM/yyyy");
		libelleDate2 = simpleFormat.format(getEndDate());
		}
		return libelleDate2;
	}

	public void setLibelleDate2(String libelleDate2) {
		this.libelleDate2 = libelleDate2;
	}

}
