package dao.Hibernate.Model;

// default package
// Generated 7 avr. 2010 17:19:09 by Hibernate Tools 3.2.2.GA

/**
 * EpsProfile generated by hbm2java
 */
public class EpsProfile implements java.io.Serializable {

	private String code;
	private String value;
	private String description;

	public EpsProfile() {
	}

	public EpsProfile(String code) {
		this.code = code;
	}

	public EpsProfile(String code, String value, String description) {
		this.code = code;
		this.value = value;
		this.description = description;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
