package dao.Hibernate.Model;
// default package
// Generated 3 sept. 2009 13:34:26 by Hibernate Tools 3.2.2.GA

/**
 * EpsPlanningId generated by hbm2java
 */
public class EpsPlanningId implements java.io.Serializable {

	private String userCode;
	private String subject;

	public EpsPlanningId() {
	}

	public EpsPlanningId(String userCode, String subject) {
		this.userCode = userCode;
		this.subject = subject;
	}

	public String getUserCode() {
		return this.userCode;
	}

	public void setUserCode(String userCode) {
		this.userCode = userCode;
	}

	public String getSubject() {
		return this.subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EpsPlanningId))
			return false;
		EpsPlanningId castOther = (EpsPlanningId) other;

		return ((this.getUserCode() == castOther.getUserCode()) || (this
				.getUserCode() != null
				&& castOther.getUserCode() != null && this.getUserCode()
				.equals(castOther.getUserCode())))
				&& ((this.getSubject() == castOther.getSubject()) || (this
						.getSubject() != null
						&& castOther.getSubject() != null && this.getSubject()
						.equals(castOther.getSubject())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getUserCode() == null ? 0 : this.getUserCode().hashCode());
		result = 37 * result
				+ (getSubject() == null ? 0 : this.getSubject().hashCode());
		return result;
	}

}
