package dao.Hibernate.Model;

// Generated 20 nov. 2009 20:02:08 by Hibernate Tools 3.2.2.GA

/**
 * GroupMenuAccess generated by hbm2java
 */
public class GroupMenuAccess implements java.io.Serializable {

	private GroupMenuAccessId id;

	public GroupMenuAccess() {
	}

	public GroupMenuAccess(GroupMenuAccessId id) {
		this.id = id;
	}

	public GroupMenuAccessId getId() {
		return this.id;
	}

	public void setId(GroupMenuAccessId id) {
		this.id = id;
	}

}
