package dao.Hibernate.Model;

// Generated 20 nov. 2009 20:02:08 by Hibernate Tools 3.2.2.GA

/**
 * GroupMenuAccessId generated by hbm2java
 */
public class GroupMenuAccessId implements java.io.Serializable {

	private String groupName;
	private String role;

	public GroupMenuAccessId() {
	}

	public GroupMenuAccessId(String groupName, String role) {
		this.groupName = groupName;
		this.role = role;
	}

	public String getGroupName() {
		return this.groupName;
	}

	public void setGroupName(String groupName) {
		this.groupName = groupName;
	}

	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof GroupMenuAccessId))
			return false;
		GroupMenuAccessId castOther = (GroupMenuAccessId) other;

		return ((this.getGroupName() == castOther.getGroupName()) || (this
				.getGroupName() != null
				&& castOther.getGroupName() != null && this.getGroupName()
				.equals(castOther.getGroupName())))
				&& ((this.getRole() == castOther.getRole()) || (this.getRole() != null
						&& castOther.getRole() != null && this.getRole()
						.equals(castOther.getRole())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getGroupName() == null ? 0 : this.getGroupName().hashCode());
		result = 37 * result
				+ (getRole() == null ? 0 : this.getRole().hashCode());
		return result;
	}

}
