package dao.Hibernate.Model;

// Generated 24 sept. 2009 13:52:36 by Hibernate Tools 3.2.2.GA

/**
 * Langue generated by hbm2java
 */
public class Langue implements java.io.Serializable {

	private String langueCode;
	private String wording;
	private String languageEmvCode;

	public Langue() {
	}

	public Langue(String langueCode) {
		this.langueCode = langueCode;
	}

	public Langue(String langueCode, String wording, String languageEmvCode) {
		this.langueCode = langueCode;
		this.wording = wording;
		this.languageEmvCode = languageEmvCode;
	}

	public String getLangueCode() {
		return this.langueCode;
	}

	public void setLangueCode(String langueCode) {
		this.langueCode = langueCode;
	}

	public String getWording() {
		return this.wording;
	}

	public void setWording(String wording) {
		this.wording = wording;
	}

	public String getLanguageEmvCode() {
		return this.languageEmvCode;
	}

	public void setLanguageEmvCode(String languageEmvCode) {
		this.languageEmvCode = languageEmvCode;
	}

}
