package dao.Hibernate.Model;

// Generated 9 avr. 2010 11:11:36 by Hibernate Tools 3.2.2.GA

import java.math.BigDecimal;

/**
 * MerchantAccount generated by hbm2java
 */
public class MerchantAccount implements java.io.Serializable {

	private String accountNumber;
	private BigDecimal balance;
	private BigDecimal deposit;

	public MerchantAccount() {
	}

	public MerchantAccount(String accountNumber) {
		this.accountNumber = accountNumber;
	}

	public MerchantAccount(String accountNumber, BigDecimal balance,
			BigDecimal deposit) {
		this.accountNumber = accountNumber;
		this.balance = balance;
		this.deposit = deposit;
	}

	public String getAccountNumber() {
		return this.accountNumber;
	}

	public void setAccountNumber(String accountNumber) {
		this.accountNumber = accountNumber;
	}

	public BigDecimal getBalance() {
		return this.balance;
	}

	public void setBalance(BigDecimal balance) {
		this.balance = balance;
	}

	public BigDecimal getDeposit() {
		return this.deposit;
	}

	public void setDeposit(BigDecimal deposit) {
		this.deposit = deposit;
	}

}
