package dao.Hibernate.Model;

/**
 * PageAccessParam generated by MyEclipse Persistence Tools
 */

public class PageAccessParam implements java.io.Serializable {

	// Fields

	private PageAccessParamId id;

	// Constructors

	/** default constructor */
	public PageAccessParam() {
	}

	/** full constructor */
	public PageAccessParam(PageAccessParamId id) {
		this.id = id;
	}

	// Property accessors

	public PageAccessParamId getId() {
		return this.id;
	}

	public void setId(PageAccessParamId id) {
		this.id = id;
	}

}