package dao.Hibernate.Model;

// Generated 1 oct. 2009 17:06:06 by Hibernate Tools 3.2.2.GA

import java.util.Date;

/**
 * TerminalFavorisId generated by hbm2java
 */
public class TerminalFavorisId implements java.io.Serializable {
	private String atmTerminalNumber;
	private String userCharging;

	public TerminalFavorisId() {
	}

	public TerminalFavorisId(String atmTerminalNumber, String userCharging) {
		this.atmTerminalNumber = atmTerminalNumber;
		this.userCharging = userCharging;
	}
	public String getAtmTerminalNumber() {
		return atmTerminalNumber;
	}

	public void setAtmTerminalNumber(String atmTerminalNumber) {
		this.atmTerminalNumber = atmTerminalNumber;
	}
	

	public String getUserCharging() {
		return this.userCharging;
	}

	public void setUserCharging(String userCharging) {
		this.userCharging = userCharging;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TerminalFavorisId))
			return false;
		TerminalFavorisId castOther = (TerminalFavorisId) other;

		return ((this.getAtmTerminalNumber() == castOther.getAtmTerminalNumber()) || (this
				.getAtmTerminalNumber() != null
				&& castOther.getAtmTerminalNumber() != null && this.getAtmTerminalNumber()
				.equals(castOther.getAtmTerminalNumber())))
				&& ((this.getUserCharging() == castOther.getUserCharging()) || (this
						.getUserCharging() != null
						&& castOther.getUserCharging() != null && this
						.getUserCharging().equals(castOther.getUserCharging())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getAtmTerminalNumber() == null ? 0 : this.getAtmTerminalNumber()
						.hashCode());
		result = 37
				* result
				+ (getUserCharging() == null ? 0 : this.getUserCharging()
						.hashCode());
		return result;
	}


}
