package dao.Hibernate.Model;

// Generated 12 avr. 2010 14:23:37 by Hibernate Tools 3.2.2.GA

import java.math.BigDecimal;
import java.util.Date;

/**
 * Transactions generated by hbm2java
 */
public class Transactions implements java.io.Serializable {

	private String idTransaction;
	private String transactionCode;
	private String customerMsisdn;
	private String merchantMsisdn;
	private Date date;
	private Character type;
	private BigDecimal amount;
	private String authCode;
	private Character statusFlag;
	private Date statusDate;
	private String memo;

	public Transactions() {
	}

	public Transactions(String idTransaction, String transactionCode) {
		this.idTransaction = idTransaction;
		this.transactionCode = transactionCode;
	}

	public Transactions(String idTransaction, String transactionCode,
			String customerMsisdn, String merchantMsisdn, Date date,
			Character type, BigDecimal amount, String authCode,
			Character statusFlag, Date statusDate, String memo) {
		this.idTransaction = idTransaction;
		this.transactionCode = transactionCode;
		this.customerMsisdn = customerMsisdn;
		this.merchantMsisdn = merchantMsisdn;
		this.date = date;
		this.type = type;
		this.amount = amount;
		this.authCode = authCode;
		this.statusFlag = statusFlag;
		this.statusDate = statusDate;
		this.memo = memo;
	}

	public String getIdTransaction() {
		return this.idTransaction;
	}

	public void setIdTransaction(String idTransaction) {
		this.idTransaction = idTransaction;
	}

	public String getTransactionCode() {
		return this.transactionCode;
	}

	public void setTransactionCode(String transactionCode) {
		this.transactionCode = transactionCode;
	}

	public String getCustomerMsisdn() {
		return this.customerMsisdn;
	}

	public void setCustomerMsisdn(String customerMsisdn) {
		this.customerMsisdn = customerMsisdn;
	}

	public String getMerchantMsisdn() {
		return this.merchantMsisdn;
	}

	public void setMerchantMsisdn(String merchantMsisdn) {
		this.merchantMsisdn = merchantMsisdn;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public Character getType() {
		return this.type;
	}

	public void setType(Character type) {
		this.type = type;
	}

	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	public String getAuthCode() {
		return this.authCode;
	}

	public void setAuthCode(String authCode) {
		this.authCode = authCode;
	}

	public Character getStatusFlag() {
		return this.statusFlag;
	}

	public void setStatusFlag(Character statusFlag) {
		this.statusFlag = statusFlag;
	}

	public Date getStatusDate() {
		return this.statusDate;
	}

	public void setStatusDate(Date statusDate) {
		this.statusDate = statusDate;
	}

	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

}
