package dao.Hibernate.Model;

// Generated 13 avr. 2010 11:00:22 by Hibernate Tools 3.2.2.GA

/**
 * TransactionDefinition generated by hbm2java
 */
public class TransactionDefinition implements java.io.Serializable {

	private String transactionCode;
	private String description;

	public TransactionDefinition() {
	}

	public TransactionDefinition(String transactionCode) {
		this.transactionCode = transactionCode;
	}

	public TransactionDefinition(String transactionCode, String description) {
		this.transactionCode = transactionCode;
		this.description = description;
	}

	public String getTransactionCode() {
		return this.transactionCode;
	}

	public void setTransactionCode(String transactionCode) {
		this.transactionCode = transactionCode;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
