package dao.Hibernate.Model;

// Generated 29 juin 2009 12:54:36 by Hibernate Tools 3.2.2.GA

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TransactionType generated by hbm2java
 */
@Entity
@Table(name = "TRANSACTION_TYPE")
public class TransactionType implements java.io.Serializable {

	private String transactionType;	
	private String wording;
	private Character signMerchant;
	private Character signCardholder;
	private Character signBank;
	private Character subjectComission;
	private String libelle1;
	private String libelle2;
	private String libelle3;
	private String libelle4;
	

	public TransactionType() {
	}


	public String getTransactionType() {
		return transactionType;
	}



	public void setTransactionType(String transactionType) {
		this.transactionType = transactionType;
	}



	@Column(name = "WORDING", length = 30)
	public String getWording() {
		return this.wording;
	}

	public void setWording(String wording) {
		this.wording = wording;
	}

	@Column(name = "SIGN_MERCHANT", length = 1)
	public Character getSignMerchant() {
		return this.signMerchant;
	}

	public void setSignMerchant(Character signMerchant) {
		this.signMerchant = signMerchant;
	}

	@Column(name = "SIGN_CARDHOLDER", length = 1)
	public Character getSignCardholder() {
		return this.signCardholder;
	}

	public void setSignCardholder(Character signCardholder) {
		this.signCardholder = signCardholder;
	}

	@Column(name = "SIGN_BANK", length = 1)
	public Character getSignBank() {
		return this.signBank;
	}

	public void setSignBank(Character signBank) {
		this.signBank = signBank;
	}

	@Column(name = "SUBJECT_COMISSION", length = 1)
	public Character getSubjectComission() {
		return this.subjectComission;
	}

	public void setSubjectComission(Character subjectComission) {
		this.subjectComission = subjectComission;
	}
	public String getLibelle1() {
		if (this.getSignMerchant().toString().equals("D")) return("Debit");
		if (this.getSignMerchant().toString().equals("C")) return("Credit");
		if (this.getSignMerchant().toString().equals("N")) return("Not Applicable");
		else return ("");
	}

	public void setLibelle1(String libelle1) {
		this.libelle1 = libelle1;
	}

	public String getLibelle2() {
		if (this.getSignCardholder().toString().equals("D")) return("Debit");
		if (this.getSignCardholder().toString().equals("C")) return("Credit");
		if (this.getSignCardholder().toString().equals("N")) return("Not Applicable");
		else return ("");
	}

	public void setLibelle2(String libelle2) {
		this.libelle2 = libelle2;
	}

	public String getLibelle3() {
		if (this.getSignBank().toString().equals("D")) return("Debit");
		if (this.getSignBank().toString().equals("C")) return("Credit");
		if (this.getSignBank().toString().equals("N")) return("Not Applicable");
		else return ("");
	}

	public void setLibelle3(String libelle3) {
		this.libelle3 = libelle3;
	}

	public String getLibelle4() {
		if (this.getSubjectComission().toString().equals("Y")) return("Yes");
		if (this.getSubjectComission().toString().equals("N")) return("No");
		else return ("");
	}

	public void setLibelle4(String libelle4) {
		this.libelle4 = libelle4;
	}


	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((signBank == null) ? 0 : signBank.hashCode());
		result = prime * result
				+ ((signCardholder == null) ? 0 : signCardholder.hashCode());
		result = prime * result
				+ ((signMerchant == null) ? 0 : signMerchant.hashCode());
		result = prime
				* result
				+ ((subjectComission == null) ? 0 : subjectComission.hashCode());
		result = prime * result
				+ ((transactionType == null) ? 0 : transactionType.hashCode());
		result = prime * result + ((wording == null) ? 0 : wording.hashCode());
		return result;
	}


	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		final TransactionType other = (TransactionType) obj;
		if (signBank == null) {
			if (other.signBank != null)
				return false;
		} else if (!signBank.equals(other.signBank))
			return false;
		if (signCardholder == null) {
			if (other.signCardholder != null)
				return false;
		} else if (!signCardholder.equals(other.signCardholder))
			return false;
		if (signMerchant == null) {
			if (other.signMerchant != null)
				return false;
		} else if (!signMerchant.equals(other.signMerchant))
			return false;
		if (subjectComission == null) {
			if (other.subjectComission != null)
				return false;
		} else if (!subjectComission.equals(other.subjectComission))
			return false;
		if (transactionType == null) {
			if (other.transactionType != null)
				return false;
		} else if (!transactionType.equals(other.transactionType))
			return false;
		if (wording == null) {
			if (other.wording != null)
				return false;
		} else if (!wording.equals(other.wording))
			return false;
		return true;
	}

	

	

}
