package dao.Hibernate.Model;

// Generated 14 sept. 2008 21:01:57 by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * UserProfile generated by hbm2java
 */
@Entity
@Table(name = "USER_PROFILE")
public class UserProfile implements java.io.Serializable {

	private String username;
	private String password;

	public UserProfile() {
	}

	public UserProfile(String username) {
		this.username = username;
	}

	public UserProfile(String username, String password) {
		this.username = username;
		this.password = password;
	}

	@Id
	@Column(name = "USERNAME", nullable = false, length = 30)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "PASSWORD", length = 30)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

}
