package dao.Hibernate.Model;
// default package
// Generated 5 août 2009 15:35:23 by Hibernate Tools 3.2.2.GA

/**
 * UserMenuAccess generated by hbm2java
 */
public class UserMenuAccess implements java.io.Serializable {

	private UserMenuAccessId id;

	public UserMenuAccess() {
	}

	public UserMenuAccess(UserMenuAccessId id) {
		this.id = id;
	}

	public UserMenuAccessId getId() {
		return this.id;
	}

	public void setId(UserMenuAccessId id) {
		this.id = id;
	}

}
