package dao.Hibernate.Model;

import java.util.Date;

/**
 * UserHabilitationParam generated by MyEclipse Persistence Tools
 */

public class UserHabilitationParam implements java.io.Serializable {

	// Fields

	private Long userHabilitationId;

	private EpsHabilitationParam epsHabilitationParam;

	private UserManagement userManagement;

	private Date startDate;

	private Date endDate;

	// Constructors

	/** default constructor */
	public UserHabilitationParam() {
	}

	/** minimal constructor */
	public UserHabilitationParam(Long userHabilitationId,
			EpsHabilitationParam epsHabilitationParam,
			UserManagement userManagement, Date startDate) {
		this.userHabilitationId = userHabilitationId;
		this.epsHabilitationParam = epsHabilitationParam;
		this.userManagement = userManagement;
		this.startDate = startDate;
	}

	/** full constructor */
	public UserHabilitationParam(Long userHabilitationId,
			EpsHabilitationParam epsHabilitationParam,
			UserManagement userManagement, Date startDate, Date endDate) {
		this.userHabilitationId = userHabilitationId;
		this.epsHabilitationParam = epsHabilitationParam;
		this.userManagement = userManagement;
		this.startDate = startDate;
		this.endDate = endDate;
	}

	// Property accessors

	public Long getUserHabilitationId() {
		return this.userHabilitationId;
	}

	public void setUserHabilitationId(Long userHabilitationId) {
		this.userHabilitationId = userHabilitationId;
	}

	public EpsHabilitationParam getEpsHabilitationParam() {
		return this.epsHabilitationParam;
	}

	public void setEpsHabilitationParam(
			EpsHabilitationParam epsHabilitationParam) {
		this.epsHabilitationParam = epsHabilitationParam;
	}

	public UserManagement getUserManagement() {
		return this.userManagement;
	}

	public void setUserManagement(UserManagement userManagement) {
		this.userManagement = userManagement;
	}

	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

}