package dao.Hibernate.Model;

// Generated 2 avr. 2010 09:55:04 by Hibernate Tools 3.2.2.GA

import java.util.Date;

/**
 * UserManagement generated by hbm2java
 */
public class UserManagement implements java.io.Serializable {

	private String userCode;
	private String userName;
	private String userType;
	private String userPassword;
	private String userBankCode;
	private String userBranchCode;
	private Long numberOfTries;
	private Long numberOfTriesAllowed;
	private String ipAddressMang;
	private String ipAddress;
	private String connected;
	private Character firstConnection;
	private Integer nbreSessionAllowed;
	private Integer nbreSessionConnected;
	private Integer lengthPassword;
	private Character complexityFlag;
	private Long expirationPassword;
	private Date dateStartPass;
	private Date dateEndPass;
	private Character blockAccess;
	private String languageCode;

	public UserManagement() {
	}

	public UserManagement(String userCode) {
		this.userCode = userCode;
	}

	public UserManagement(String userCode, String userName, String userType,
			String userPassword, String userBankCode, String userBranchCode,
			Long numberOfTries, Long numberOfTriesAllowed,
			String ipAddressMang, String ipAddress, String connected,
			Character firstConnection, Integer nbreSessionAllowed,
			Integer nbreSessionConnected, Integer lengthPassword,
			Character complexityFlag, Long expirationPassword,
			Date dateStartPass, Date dateEndPass, Character blockAccess,
			String languageCode) {
		this.userCode = userCode;
		this.userName = userName;
		this.userType = userType;
		this.userPassword = userPassword;
		this.userBankCode = userBankCode;
		this.userBranchCode = userBranchCode;
		this.numberOfTries = numberOfTries;
		this.numberOfTriesAllowed = numberOfTriesAllowed;
		this.ipAddressMang = ipAddressMang;
		this.ipAddress = ipAddress;
		this.connected = connected;
		this.firstConnection = firstConnection;
		this.nbreSessionAllowed = nbreSessionAllowed;
		this.nbreSessionConnected = nbreSessionConnected;
		this.lengthPassword = lengthPassword;
		this.complexityFlag = complexityFlag;
		this.expirationPassword = expirationPassword;
		this.dateStartPass = dateStartPass;
		this.dateEndPass = dateEndPass;
		this.blockAccess = blockAccess;
		this.languageCode = languageCode;
	}

	public String getUserCode() {
		return this.userCode;
	}

	public void setUserCode(String userCode) {
		this.userCode = userCode;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getUserType() {
		return this.userType;
	}

	public void setUserType(String userType) {
		this.userType = userType;
	}

	public String getUserPassword() {
		return this.userPassword;
	}

	public void setUserPassword(String userPassword) {
		this.userPassword = userPassword;
	}

	public String getUserBankCode() {
		return this.userBankCode;
	}

	public void setUserBankCode(String userBankCode) {
		this.userBankCode = userBankCode;
	}

	public String getUserBranchCode() {
		return this.userBranchCode;
	}

	public void setUserBranchCode(String userBranchCode) {
		this.userBranchCode = userBranchCode;
	}

	public Long getNumberOfTries() {
		return this.numberOfTries;
	}

	public void setNumberOfTries(Long numberOfTries) {
		this.numberOfTries = numberOfTries;
	}

	public Long getNumberOfTriesAllowed() {
		return this.numberOfTriesAllowed;
	}

	public void setNumberOfTriesAllowed(Long numberOfTriesAllowed) {
		this.numberOfTriesAllowed = numberOfTriesAllowed;
	}

	public String getIpAddressMang() {
		return this.ipAddressMang;
	}

	public void setIpAddressMang(String ipAddressMang) {
		this.ipAddressMang = ipAddressMang;
	}

	public String getIpAddress() {
		return this.ipAddress;
	}

	public void setIpAddress(String ipAddress) {
		this.ipAddress = ipAddress;
	}

	public String getConnected() {
		return this.connected;
	}

	public void setConnected(String connected) {
		this.connected = connected;
	}

	public Character getFirstConnection() {
		return this.firstConnection;
	}

	public void setFirstConnection(Character firstConnection) {
		this.firstConnection = firstConnection;
	}

	public Integer getNbreSessionAllowed() {
		return this.nbreSessionAllowed;
	}

	public void setNbreSessionAllowed(Integer nbreSessionAllowed) {
		this.nbreSessionAllowed = nbreSessionAllowed;
	}

	public Integer getNbreSessionConnected() {
		return this.nbreSessionConnected;
	}

	public void setNbreSessionConnected(Integer nbreSessionConnected) {
		this.nbreSessionConnected = nbreSessionConnected;
	}

	public Integer getLengthPassword() {
		return this.lengthPassword;
	}

	public void setLengthPassword(Integer lengthPassword) {
		this.lengthPassword = lengthPassword;
	}

	public Character getComplexityFlag() {
		return this.complexityFlag;
	}

	public void setComplexityFlag(Character complexityFlag) {
		this.complexityFlag = complexityFlag;
	}

	public Long getExpirationPassword() {
		return this.expirationPassword;
	}

	public void setExpirationPassword(Long expirationPassword) {
		this.expirationPassword = expirationPassword;
	}

	public Date getDateStartPass() {
		return this.dateStartPass;
	}

	public void setDateStartPass(Date dateStartPass) {
		this.dateStartPass = dateStartPass;
	}

	public Date getDateEndPass() {
		return this.dateEndPass;
	}

	public void setDateEndPass(Date dateEndPass) {
		this.dateEndPass = dateEndPass;
	}

	public Character getBlockAccess() {
		return this.blockAccess;
	}

	public void setBlockAccess(Character blockAccess) {
		this.blockAccess = blockAccess;
	}

	public String getLanguageCode() {
		return this.languageCode;
	}

	public void setLanguageCode(String languageCode) {
		this.languageCode = languageCode;
	}

}
