package dao.Hibernate.Model;
// default package
// Generated 5 août 2009 15:35:23 by Hibernate Tools 3.2.2.GA

/**
 * UserMenuAccessId generated by hbm2java
 */
public class UserMenuAccessId implements java.io.Serializable {

	private String role;
	private String menuName;

	public UserMenuAccessId() {
	}

	public UserMenuAccessId(String role, String menuName) {
		this.role = role;
		this.menuName = menuName;
	}

	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	public String getMenuName() {
		return this.menuName;
	}

	public void setMenuName(String menuName) {
		this.menuName = menuName;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserMenuAccessId))
			return false;
		UserMenuAccessId castOther = (UserMenuAccessId) other;

		return ((this.getRole() == castOther.getRole()) || (this.getRole() != null
				&& castOther.getRole() != null && this.getRole().equals(
				castOther.getRole())))
				&& ((this.getMenuName() == castOther.getMenuName()) || (this
						.getMenuName() != null
						&& castOther.getMenuName() != null && this
						.getMenuName().equals(castOther.getMenuName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getRole() == null ? 0 : this.getRole().hashCode());
		result = 37 * result
				+ (getMenuName() == null ? 0 : this.getMenuName().hashCode());
		return result;
	}

}
