package dao.Hibernate.Model;

// Generated 2 oct. 2009 11:10:31 by Hibernate Tools 3.2.2.GA

import java.math.BigDecimal;
import java.util.Date;

/**
 * VListOfClaimId generated by hbm2java
 */
public class VListOfClaimId implements java.io.Serializable {


	private String callId;
	
	

	public VListOfClaimId() {
	}

	public VListOfClaimId(String callId) {
		this.callId = callId;
				
	}

	public String getCallId() {
		return callId;
	}

	public void setCallId(String callId) {
		this.callId = callId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VListOfClaimId))
			return false;
		VListOfClaimId castOther = (VListOfClaimId) other;

		return ((this.getCallId() == castOther.getCallId()) || (this
				.getCallId() != null
				&& castOther.getCallId() != null && this.getCallId()
				.equals(castOther.getCallId())))
				
				;
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getCallId() == null ? 0 : this.getCallId()
						.hashCode());
		
		
		return result;
	}


	

}
