package web.view;

// default package
// Generated 31 mars 2010 11:08:08 by Hibernate Tools 3.2.2.GA

import java.math.BigDecimal;

/**
 * CustomerAccount generated by hbm2java
 */
public class CustomerAccountBV implements java.io.Serializable {

	private String accountNumber;
	private BigDecimal balance;

	public CustomerAccountBV() {
	}

	public CustomerAccountBV(String accountNumber) {
		this.accountNumber = accountNumber;
	}

	public CustomerAccountBV(String accountNumber, BigDecimal balance) {
		this.accountNumber = accountNumber;
		this.balance = balance;
	}

	public String getAccountNumber() {
		return this.accountNumber;
	}

	public void setAccountNumber(String accountNumber) {
		this.accountNumber = accountNumber;
	}

	public BigDecimal getBalance() {
		return this.balance;
	}

	public void setBalance(BigDecimal balance) {
		this.balance = balance;
	}

}
