package web.controller;

// default package
// Generated 31 mars 2010 11:08:08 by Hibernate Tools 3.2.2.GA

import dao.Hibernate.Model.CustomerAccount;
import web.view.CustomerAccountBV;

import dao.DAO;

/**
 * CustomerAccount generated by hbm2java
 */
public class CustomerAccountBC implements java.io.Serializable {

	private CustomerAccountBV beanView; // instance du bean lié aux composants de la vue.
	DAO dao=new DAO();

	public CustomerAccountBC() {
	}

	public String accountAction(){  
		

		CustomerAccount acc=new CustomerAccount();
		acc.setAccountNumber(beanView.getAccountNumber());
		acc.setBalance(beanView.getBalance());
		dao.save(acc);
		return null;
	}

	public CustomerAccountBV getBeanView() {
		return beanView;
	}

	public void setBeanView(CustomerAccountBV beanView) {
		this.beanView = beanView;
	}


	
	

}
